import {test,expect,Page} from '@playwright/test';
import path from 'node:path';
import {startUtilityServer} from '../../scripts/utility-poc-server.mjs';
let service:Awaited<ReturnType<typeof startUtilityServer>>;
test.beforeAll(async()=>{service=await startUtilityServer();});test.afterAll(async()=>{await service.close();});
const url=(kind:string)=>`${service.base}/docs/research/2026-09-20-admin-keys-poc/${kind}.html`;
async function issue(page:Page){await page.locator('#issue').click();await expect(page.locator('#once')).toBeVisible();await expect(page.locator('#value')).toHaveValue(/^DEMO-NOT-A-CREDENTIAL-/);}
async function closeValue(page:Page){await page.locator('#forget').click();await expect(page.locator('#value')).toHaveValue('');await expect(page.locator('#once')).toBeHidden();}
async function inject(page:Page,value:string){await page.locator('details').last().evaluate(e=>e.setAttribute('open',''));await page.locator('#failure').selectOption(value);}
for(const kind of ['readonly','writer','revoked'])for(const width of [1440,390,320])for(const js of [true,false])test(`AC-A ${kind} ${width}px ${js?'js':'no-js'} permission and reflow`,async({browser},info)=>{
 const context=await browser.newContext({viewport:{width,height:1000},javaScriptEnabled:js});const page=await context.newPage();try{await page.goto(url(kind));await expect(page.locator('[aria-current=page]')).toHaveAttribute('href',`${kind}.html`);await expect(page.locator('.boundary')).toContainText('Application Passwords');
 if(js){await issue(page);await closeValue(page);if(kind==='revoked')await page.locator('#revoke').click();await page.locator('#write').click();await expect(page.locator('#access-result')).toContainText(kind==='writer'?'許可':'拒否');await expect(page.locator('#value')).toHaveValue('');expect(await page.locator('body').innerText()).not.toContain('DEMO-NOT-A-CREDENTIAL-');
 if(width!==320){await page.locator('header').click();await page.screenshot({path:process.env.ADMIN_KEYS_CAPTURE_DIR?path.join(process.env.ADMIN_KEYS_CAPTURE_DIR,`${kind}-${width===1440?'pc':'sp'}.jpg`):info.outputPath(`${kind}.jpg`),fullPage:true,type:'jpeg',quality:85});}}
 else{await expect(page.locator('.nojs')).toContainText('JavaScriptが無効');await page.locator('#issue').click();await expect(page.locator('#value')).toHaveValue('');await expect(page.locator('#record-status')).toHaveText('未発行');}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('footer')).toContainText('未検証');}finally{await context.close();}
});
test('AC-A one-time issuance focuses value and prevents duplicate issue while visible',async({page})=>{await page.goto(url('readonly'));await issue(page);await expect(page.locator('#once')).toBeFocused();const value=await page.locator('#value').inputValue();await page.locator('#issue').click();await expect(page.locator('#error-code')).toContainText('CLOSE_FIRST');await expect(page.locator('#record option')).toHaveCount(1);await expect(page.locator('#value')).toHaveValue(value);await page.locator('#select-value').click();expect(await page.locator('#value').evaluate((e:HTMLTextAreaElement)=>e.selectionEnd-e.selectionStart)).toBe(value.length);await closeValue(page);await issue(page);expect(await page.locator('#value').inputValue()).not.toBe(value);await expect(page.locator('#record option')).toHaveCount(2);await page.locator('#record').selectOption({index:0});await expect(page.locator('#value')).toHaveValue('');await expect(page.locator('#once')).toBeHidden();});
test('AC-B reveal remains denied after display controls are bypassed',async({page})=>{await page.goto(url('readonly'));await issue(page);await closeValue(page);await page.locator('#reveal').evaluate(e=>e.removeAttribute('aria-disabled'));await page.locator('#reveal').click({force:true});await expect(page.locator('#error-code')).toContainText('VALUE_NOT_RETRIEVABLE');await expect(page.locator('#value')).toHaveValue('');await expect(page.locator('#once')).toBeHidden();await expect(page.locator('#log')).not.toContainText('DEMO-NOT-A-CREDENTIAL-');});
test('AC-B per-record permissions survive role picker and display tampering',async({page})=>{await page.goto(url('readonly'));await issue(page);await closeValue(page);const reader=await page.locator('#record').inputValue();await page.locator('[name=permission][value=write]').check();await page.locator('#write').click();await expect(page.locator('#access-result')).toContainText('拒否');await issue(page);await closeValue(page);const writer=await page.locator('#record').inputValue();await page.locator('#write').click();await expect(page.locator('#access-result')).toContainText('許可');await page.locator('#record').selectOption(reader);await page.locator('#record-permission').evaluate(e=>e.textContent='書き込み可');await page.locator('#write').click();await expect(page.locator('#access-result')).toContainText('拒否');await page.locator('#read').click();await expect(page.locator('#access-result')).toContainText('許可');await page.locator('#revoke').click();for(const op of ['read','write']){await page.locator('#'+op).click();await expect(page.locator('#access-result')).toContainText('拒否');}await page.locator('#record').selectOption(writer);await expect(page.locator('#record-status')).toContainText('有効');await page.locator('#write').click();await expect(page.locator('#access-result')).toContainText('許可');});
test('AC-B revocation clears a visible value and repeated revoke cannot restore it',async({page})=>{await page.goto(url('writer'));await issue(page);await page.locator('#revoke').click();await expect(page.locator('#value')).toHaveValue('');await expect(page.locator('#once')).toBeHidden();await expect(page.locator('#record-status')).toContainText('失効済み');await page.locator('#revoke').click({force:true});await expect(page.locator('#error-code')).toContainText('ALREADY_REVOKED');await page.locator('#read').click();await expect(page.locator('#access-result')).toContainText('拒否');});
for(const action of ['issue','revoke'])test(`AC-A ${action} failure and retry preserve accurate state`,async({page})=>{await page.goto(url('readonly'));if(action==='revoke'){await issue(page);await closeValue(page);}await inject(page,action);await page.locator('#'+action).click();await expect(page.locator('#error')).toBeFocused();await expect(page.locator('#error-code')).toContainText(action==='issue'?'ISSUE_FAILED':'REVOKE_FAILED');await expect(page.locator('#record-status')).toHaveText(action==='issue'?'未発行':'有効（デモ）');await expect(page.locator('#value')).toHaveValue('');if(action==='issue')await expect(page.locator('#record option[value=""]')).toHaveCount(1);await expect(page.locator('#log')).toContainText('失敗');await page.locator('#retry').click();await expect(page.locator('#error')).toBeHidden();await expect(page.locator('#record-status')).toHaveText(action==='issue'?'有効（デモ）':'失効済み（デモ）');if(action==='issue')await closeValue(page);});
test('AC-B invalid permission cannot issue even when injected into picker',async({page})=>{await page.goto(url('readonly'));await page.locator('[name=permission]:checked').evaluate((e:HTMLInputElement)=>e.value='admin');await page.locator('#issue').click();await expect(page.locator('#error-code')).toContainText('INVALID_PERMISSION');await expect(page.locator('#record-status')).toHaveText('未発行');await expect(page.locator('#value')).toHaveValue('');});
test('AC-A keyboard issue hide revoke and 200 percent root text',async({page})=>{await page.setViewportSize({width:390,height:1000});await page.goto(url('readonly'));await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');await page.locator('[name=permission][value=read]').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('[name=permission][value=write]')).toBeChecked();await page.keyboard.press('Tab');await expect(page.locator('#issue')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#once')).toBeFocused();await page.locator('#forget').focus();await page.keyboard.press('Enter');await expect(page.locator('#issue')).toBeFocused();await page.locator('#revoke').focus();await page.keyboard.press('Enter');await expect(page.locator('#record-status')).toContainText('失効済み');await page.addStyleTag({content:':root{font-size:32px}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('AC-B no persistence cookies requests logs or metadata retain issued value',async({page})=>{const writes:string[]=[],requests:string[]=[],allRequests:string[]=[],logs:string[]=[];await page.exposeFunction('recordStore',(key:string)=>writes.push(key));await page.addInitScript(()=>{Storage.prototype.setItem=function(key:string){void(window as unknown as {recordStore:(key:string)=>void}).recordStore(key);};});page.on('request',r=>{allRequests.push(r.url());if(r.method()!=='GET')requests.push(r.url());});page.on('console',m=>logs.push(m.text()));await page.goto(url('readonly'));await issue(page);const value=await page.locator('#value').inputValue();await expect(page.locator('#log')).not.toContainText(value);await expect(page.locator('.metadata')).not.toContainText(value);await closeValue(page);expect(await page.content()).not.toContain(value);await page.reload();await expect(page.locator('#value')).toHaveValue('');await expect(page.locator('#record-status')).toHaveText('未発行');expect(writes).toEqual([]);expect(requests).toEqual([]);expect(allRequests.every(u=>u.startsWith(service.base+'/docs/research/'))).toBe(true);expect(allRequests.join('\n')).not.toContain(value);expect(logs.join('\n')).not.toContain(value);expect(await page.context().cookies()).toEqual([]);});
