import {test,expect,Page} from '@playwright/test';
import path from 'node:path';
import {startUtilityServer} from '../../scripts/utility-poc-server.mjs';
let service:Awaited<ReturnType<typeof startUtilityServer>>;
test.beforeAll(async()=>{service=await startUtilityServer();});test.afterAll(async()=>{await service.close();});
const url=(kind:string)=>`${service.base}/docs/research/2026-09-20-admin-changes-poc/${kind}.html`;
async function review(page:Page){await page.locator('#dryrun').click();await page.locator('#confirm').check();}
async function inject(page:Page,value:string){await page.locator('details').evaluate(e=>e.setAttribute('open',''));await page.locator('#failure').selectOption(value);}
for(const kind of ['review','blocked','recovery'])for(const width of [1440,390,320])for(const js of [true,false])test(`AC-A ${kind} ${width}px ${js?'js':'no-js'} diff and reflow`,async({browser},info)=>{
 const context=await browser.newContext({viewport:{width,height:1000},javaScriptEnabled:js});const page=await context.newPage();try{
 await page.goto(url(kind));await expect(page.locator('.diff')).toHaveCount(3);await expect(page.locator('[aria-current=page]')).toHaveAttribute('href',`${kind}.html`);
 if(js){await review(page);if(kind==='blocked')await expect(page.locator('#state')).toHaveText('破壊域停止');if(kind==='recovery'){await inject(page,'partial');await page.locator('#apply').click();await expect(page.locator('#state')).toHaveText('部分適用・未完了');await page.locator('details').evaluate(e=>e.removeAttribute('open'));}
 if(width!==320){await page.locator('header').click();await page.screenshot({path:process.env.ADMIN_CHANGES_CAPTURE_DIR?path.join(process.env.ADMIN_CHANGES_CAPTURE_DIR,`${kind}-${width===1440?'pc':'sp'}.jpg`):info.outputPath(`${kind}.jpg`),fullPage:true,type:'jpeg',quality:85});}}
 else{await expect(page.locator('.nojs')).toContainText('JavaScriptが無効');await page.locator('#dryrun').click();await expect(page.locator('#state')).toHaveText('未検査');await page.locator('#apply').click({force:true});await expect(page.locator('#current-toc')).toHaveText('auto');}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('footer')).toContainText('未検証');
 }finally{await context.close();}
});
test('AC-A review apply rollback logs and restores all values',async({page})=>{await page.goto(url('review'));await review(page);await page.locator('#apply').click();await expect(page.locator('#current-toc')).toHaveText('off');await expect(page.locator('#current-threshold')).toHaveText('4');await expect(page.locator('#log')).toContainText('適用済み');await page.locator('#rollback').click();await expect(page.locator('#current-toc')).toHaveText('auto');await expect(page.locator('#current-threshold')).toHaveText('3');await expect(page.locator('#current-protected')).toHaveText('保持');await expect(page.locator('#log')).toContainText('復旧済み');expect(await page.locator('#log li').count()).toBe(3);});
for(const action of ['reject','hold'])test(`AC-B ${action} prevents subsequent apply until fresh review`,async({page})=>{await page.goto(url('review'));await review(page);await page.locator('#'+action).click();await page.locator('#apply').click({force:true});await expect(page.locator('#current-toc')).toHaveText('auto');await expect(page.locator('#error-id')).toHaveValue(/REVIEW_REQUIRED/);await expect(page.locator('#confirm')).not.toBeChecked();await expect(page.locator('#log')).toContainText(action==='reject'?'却下済み':'保留中');await review(page);await page.locator('#apply').click();await expect(page.locator('#current-toc')).toHaveText('off');});
test('AC-B bypassing disabled display cannot bypass review or destructive stop',async({page})=>{await page.goto(url('review'));await page.locator('#confirm').check();await page.locator('#apply').evaluate(e=>e.removeAttribute('aria-disabled'));await page.locator('#apply').click();await expect(page.locator('#current-toc')).toHaveText('auto');await page.goto(url('blocked'));await review(page);await page.locator('#apply').evaluate(e=>e.removeAttribute('aria-disabled'));await page.locator('#apply').click();await expect(page.locator('#current-protected')).toHaveText('保持');await expect(page.locator('#current-toc')).toHaveText('auto');await expect(page.locator('#state')).toHaveText('破壊域停止');await expect(page.locator('#error-id')).toHaveValue(/REVIEW_REQUIRED/);});
test('AC-B reviewed but unconfirmed apply is blocked even when display guard is removed',async({page})=>{await page.goto(url('review'));await page.locator('#dryrun').click();await expect(page.locator('#state')).toHaveText('検査済み・未適用');await expect(page.locator('#confirm')).not.toBeChecked();await page.locator('#apply').evaluate(e=>e.removeAttribute('aria-disabled'));await page.locator('#apply').click({force:true});await expect(page.locator('#current-toc')).toHaveText('auto');await expect(page.locator('#state')).toHaveText('検査済み・未適用');await expect(page.locator('#error-id')).toHaveValue(/REVIEW_REQUIRED/);await expect(page.locator('#log')).not.toContainText('適用済み');});
for(const action of ['dryrun','apply','reject','rollback'])test(`AC-C ${action} failure preserves diff and retry recovers with logs`,async({page})=>{await page.goto(url('review'));if(action!=='dryrun')await review(page);if(action==='rollback')await page.locator('#apply').click();const before=[await page.locator('#current-toc').innerText(),await page.locator('#current-threshold').innerText()];await inject(page,action);await page.locator('#'+action).click();await expect(page.locator('#diagnostic')).toBeFocused();await expect(page.locator('#error-id')).toHaveValue(/LOCAL-/);await expect(page.locator('#recovery-context')).toContainText('DEMO-001');expect([await page.locator('#current-toc').innerText(),await page.locator('#current-threshold').innerText()]).toEqual(before);await expect(page.locator('.diff')).toHaveCount(3);await expect(page.locator('#log')).toContainText('失敗');await page.locator('#retry').click();await expect(page.locator('#diagnostic')).toBeHidden();await expect(page.locator('#log')).toContainText(action==='dryrun'?'検査済み':action==='apply'?'適用済み':action==='reject'?'却下済み':'復旧済み');});
test('AC-C partial apply is incomplete and rollback failure keeps recovery context',async({page})=>{await page.goto(url('recovery'));await review(page);await inject(page,'partial');await page.locator('#apply').click();await expect(page.locator('#state')).toHaveText('部分適用・未完了');await expect(page.locator('#current-toc')).toHaveText('off');await expect(page.locator('#current-threshold')).toHaveText('3');await expect(page.locator('#log')).not.toContainText('適用済み');await page.locator('#apply').click({force:true});await expect(page.locator('#current-threshold')).toHaveText('3');await inject(page,'rollback');await page.locator('#rollback').click();await expect(page.locator('#error-id')).toHaveValue(/ROLLBACK_UNAVAILABLE/);await page.locator('#retry').click();await expect(page.locator('#current-toc')).toHaveText('auto');await expect(page.locator('#state')).toHaveText('復旧済み（未保存）');await expect(page.locator('#log')).toContainText('失敗');await expect(page.locator('#log')).toContainText('復旧済み');});
for(const denied of [false,true])test(`AC-C diagnostic copy ${denied?'fallback':'success'}`,async({page})=>{await page.addInitScript(({denied})=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async(value:string)=>{if(denied)throw Error('denied');(window as unknown as {copied:string}).copied=value;}}});},{denied});await page.goto(url('review'));await inject(page,'dryrun');await page.locator('#dryrun').click();await page.locator('#copy').click();if(denied){await expect(page.locator('#copy-status')).toContainText('手動でコピー');await expect(page.locator('#error-id')).toBeFocused();expect(await page.locator('#error-id').evaluate((e:HTMLTextAreaElement)=>e.selectionEnd-e.selectionStart)).toBeGreaterThan(10);}else{await expect(page.locator('#copy-status')).toContainText('コピーしました');expect(await page.evaluate(()=>(window as unknown as {copied:string}).copied)).toBe(await page.locator('#error-id').inputValue());}});
test('AC-A keyboard review and rollback at 200 percent root text',async({page})=>{await page.setViewportSize({width:390,height:1000});await page.goto(url('review'));await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');await page.locator('#dryrun').focus();await page.keyboard.press('Enter');await page.keyboard.press('Tab');await expect(page.locator('#confirm')).toBeFocused();await page.keyboard.press('Space');await page.keyboard.press('Tab');await expect(page.locator('#apply')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#current-toc')).toHaveText('off');await page.locator('#rollback').focus();await page.keyboard.press('Enter');await expect(page.locator('#current-toc')).toHaveText('auto');await page.addStyleTag({content:':root{font-size:32px}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('AC-B operations stay transient and emit no external writes',async({page})=>{const posts:string[]=[];page.on('request',r=>{if(r.method()!=='GET')posts.push(r.url());});await page.goto(url('review'));await review(page);await page.locator('#apply').click();expect(await page.evaluate(()=>localStorage.length+sessionStorage.length)).toBe(0);expect(await page.context().cookies()).toEqual([]);expect(posts).toEqual([]);await page.reload();await expect(page.locator('#state')).toHaveText('未検査');await expect(page.locator('#log')).toContainText('まだ操作していません');});
