import {test,expect} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';
import {startProductServer} from '../../scripts/product-surfaces-server.mjs';import {fixture,copy,trail,projection,scenarios} from '../../docs/research/2026-09-20-breadcrumb-poc/model.mjs';
let service;test.beforeAll(async()=>service=await startProductServer());test.afterAll(async()=>service.close());const url=id=>`${service.base}/docs/research/2026-09-20-breadcrumb-poc/${id}.html`;
async function match(page,source,id){const expected=trail(source,id),links=page.locator('#breadcrumb a');await expect(links).toHaveText(expected.map(x=>x.name));expect(await links.evaluateAll(es=>es.map(e=>e.getAttribute('href')))).toEqual(expected.map(x=>x.url));const json=JSON.parse(await page.locator('#breadcrumb-json').textContent());expect(json.itemListElement).toEqual(expected.map(x=>({'@type':'ListItem',position:x.position,name:x.name,item:x.url})));await expect(page.locator('#breadcrumb [aria-current=page]')).toHaveCount(1);await expect(page.locator('#breadcrumb [aria-current=page]')).toHaveText(source.nodes[id].name);await expect(page.locator('#page-title')).toHaveText(source.nodes[id].name);}
for(const s of scenarios)for(const width of [1440,390,320])for(const js of [true,false])test(`AC-A ${s.id} ${width} ${js?'js':'no-js'} visible breadcrumb and JSON-LD match`,async({browser},info)=>{const context=await browser.newContext({viewport:{width,height:1000},javaScriptEnabled:js});try{const page=await context.newPage();await page.goto(url(s.id));await match(page,fixture,s.id);await expect(page.getByRole('navigation',{name:'パンくず',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(!js){await expect(page.locator('#apply')).toBeDisabled();await expect(page.locator('.notice')).toBeVisible();}if(js&&width!==320){await page.evaluate(()=>document.fonts.ready);const dir=process.env.BREADCRUMB_CAPTURE_DIR||info.outputDir;fs.mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,`${s.id}-${width===1440?'pc':'sp'}.jpg`),type:'jpeg',quality:78,fullPage:true});}}finally{await context.close();}});
for(const id of ['post','page','lp'])test(`AC-A ${id} canonical name parent path changes both visible and JSON-LD`,async({page})=>{await page.goto(url(id));const next=copy(fixture);next.nodes[id]={...next.nodes[id],name:'変更した案内の名前',path:'/new-location/',parent:'guide'};await page.locator('#name').fill(next.nodes[id].name);await page.locator('#path').fill(next.nodes[id].path);await page.locator('#parent').selectOption('guide');await page.locator('#apply').click();await match(page,next,id);await page.locator('#reset').click();await match(page,fixture,id);});
for(const [label,parent,pathValue]of [['missing','missing','/valid/'],['cycle','post','/valid/'],['unsafe','home','//outside.invalid/'],['query','home','/valid/?key=1']])test(`AC-B ${label} stops projection and preserves prior display`,async({page})=>{await page.goto(url('post'));const before=await page.locator('#breadcrumb').innerHTML(),json=await page.locator('#breadcrumb-json').textContent();await page.locator('#parent').selectOption(parent);await page.locator('#path').fill(pathValue);await page.locator('#apply').click();await expect(page.locator('#status')).toContainText('更新を停止');expect(await page.locator('#breadcrumb').innerHTML()).toBe(before);expect(await page.locator('#breadcrumb-json').textContent()).toBe(json);});
test('AC-B deep cycle empty name and one-node output are rejected',()=>{const cycle=copy(fixture);cycle.nodes.journal.parent='post';expect(()=>projection(cycle,'post')).toThrow('循環');const empty=copy(fixture);empty.nodes.post.name=' ';expect(()=>projection(empty,'post')).toThrow('表示名');expect(()=>projection(fixture,'home')).toThrow('2階層');});
test('AC-A LP uses semantic parent and directory independent URL with recorded boundary',async({page})=>{await page.goto(url('lp'));expect(trail(fixture,'lp').map(x=>x.id)).toEqual(['home','services','consult','lp']);await expect(page.locator('#breadcrumb a').last()).toHaveAttribute('href','https://example.com/desk-session/');await expect(page.locator('.url-note')).toContainText('ディレクトリ非依存URL');await expect(page.locator('.url-note')).toContainText('未検証');});
test('AC-B altered ancestor name and URL are derived without hand-written trail',()=>{const next=copy(fixture);next.nodes.guide.name='変更した祖先';next.nodes.guide.path='/new-guide/';const result=projection(next,'page');expect(result.items[1]).toMatchObject({name:'変更した祖先',url:'https://example.com/new-guide/'});expect(result.html).toContain('>変更した祖先</a>');expect(result.json.itemListElement[1].name).toBe('変更した祖先');});
test('AC-A keyboard and 200 percent root text preserve long labels',async({page})=>{await page.setViewportSize({width:390,height:1000});await page.goto(url('page'));await page.addStyleTag({content:':root{font-size:32px}'});await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#content')).toBeFocused();await page.locator('#breadcrumb a').first().focus();await page.keyboard.press('Tab');await expect(page.locator('#breadcrumb a').nth(1)).toBeFocused();await match(page,fixture,'page');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.locator('#breadcrumb a').last().evaluate(e=>getComputedStyle(e).textOverflow)).not.toBe('ellipsis');});
test('AC-A local editing and click do not send or persist data',async({page})=>{const requests=[];page.on('request',r=>requests.push(r.url()));await page.goto(url('post'));await page.locator('#name').fill('ローカルの変更');await page.locator('#apply').click();await page.locator('#breadcrumb a').first().click();await expect(page.locator('#status')).toContainText('外部へ移動しません');expect(requests.every(u=>u.startsWith(service.base+'/docs/research/'))).toBe(true);expect(await page.evaluate(()=>[localStorage.length,sessionStorage.length])).toEqual([0,0]);expect(await page.context().cookies()).toEqual([]);await page.reload();await match(page,fixture,'post');});
