import {test,expect} from '@playwright/test';
import path from 'node:path';
import {startProductServer} from '../../scripts/product-surfaces-server.mjs';
import {catalog,surfaces,variantId} from '../../docs/research/2026-09-20-product-surfaces-poc/products.mjs';
import {renderPage,structured} from '../../scripts/product-surfaces-renderer.mjs';
let service:Awaited<ReturnType<typeof startProductServer>>;
test.beforeAll(async()=>{service=await startProductServer();});test.afterAll(async()=>{await service.close();});
const url=(kind:string)=>`${service.base}/docs/research/2026-09-20-product-surfaces-poc/${kind}.html`;
for(const f of surfaces)for(const width of [1440,390,320])for(const js of [true,false])test(`AC-A ${f.id} ${width}px ${js?'js':'no-js'} canonical values and reflow`,async({browser},info)=>{
 const context=await browser.newContext({viewport:{width,height:1000},javaScriptEnabled:js});const page=await context.newPage();try{await page.goto(url(f.id));await expect(page.locator('h1')).toHaveText(f.label);const graph=JSON.parse(await page.locator('script[type="application/ld+json"]').textContent()||'{}')['@graph'];
 for(const p of catalog.products){const node=graph.find(x=>x.sku===p.id);expect(node.name).toBe(p.name);expect(node.offers.price).toBe(p.price);expect(node.aggregateRating.ratingValue).toBe(p.rating);expect(node.aggregateRating.ratingCount).toBe(p.ratingCount);await expect(page.getByRole('heading',{name:p.name,exact:true})).toBeVisible();await expect(page.locator(`[data-price="${p.price}"]`)).toHaveText(`${p.price.toLocaleString('ja-JP')}円`);await expect(page.locator(`[data-rating="${p.rating}"]`)).toContainText(`架空 ${p.ratingCount} 件`);const image=page.getByAltText(`${p.name}の架空イラスト`);expect(await image.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true);expect(Boolean(node.offers.shippingDetails)).toBe(p.linkType==='self-ec');expect(Boolean(node.offers.hasMerchantReturnPolicy)).toBe(p.linkType==='self-ec');}
 expect(graph.find(x=>x['@type']==='ItemList').itemListElement).toHaveLength(3);await expect(page.locator('[data-policy-product=light-c]')).toContainText('14日以内');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(!js){await expect(page.locator('.nojs')).toContainText('JavaScriptが無効');await page.locator('.cta').first().click();await expect(page).toHaveURL(/#demo-destination$/);await expect(page.locator('#event-status')).toHaveText('まだ操作していません。');}
 if(js&&width!==320){await page.locator('header').click();await page.screenshot({path:process.env.PRODUCT_CAPTURE_DIR?path.join(process.env.PRODUCT_CAPTURE_DIR,`${f.id}-${width===1440?'pc':'sp'}.jpg`):info.outputPath(`${f.id}.jpg`),fullPage:true,type:'jpeg',quality:85});}
 }finally{await context.close();}
});
for(const f of surfaces)test(`AC-A ${f.id} CTA emits both IDs locally without external writes`,async({page})=>{const events:unknown[]=[],requests:string[]=[];await page.exposeFunction('captureEvent',(value:unknown)=>events.push(value));await page.addInitScript(()=>document.addEventListener('helix:product-conversion',(event:CustomEvent)=>{void(window as unknown as {captureEvent:(value:unknown)=>void}).captureEvent(event.detail);}));page.on('request',r=>requests.push(r.url()));await page.goto(url(f.id));for(const p of catalog.products){await page.locator(`.cta[data-product-id=${p.id}]`).click();await expect(page.locator('#demo-destination')).toBeFocused();await expect(page.locator('#event-status')).toContainText('外部送信・購入は行っていません');}expect(events).toEqual(catalog.products.map(p=>({productId:p.id,variantId:variantId(f.id),goalCvId:p.goalCvId,linkType:p.linkType,surface:f.id})));expect(requests.every(u=>u.startsWith(service.base+'/docs/research/'))).toBe(true);expect(await page.context().cookies()).toEqual([]);});
for(const attribute of ['data-variant-id','data-goal-cv-id'])test(`AC-B missing ${attribute} blocks conversion projection`,async({page})=>{const events:unknown[]=[];await page.exposeFunction('captureEvent',(value:unknown)=>events.push(value));await page.addInitScript(()=>document.addEventListener('helix:product-conversion',(event:CustomEvent)=>{void(window as unknown as {captureEvent:(value:unknown)=>void}).captureEvent(event.detail);}));await page.goto(url('comparison'));await page.locator('.cta').first().evaluate((e,a)=>e.removeAttribute(a),attribute);await page.locator('.cta').first().click();await expect(page.locator('#event-status')).toContainText('IDが不足');expect(events).toEqual([]);});
test('AC-A comparison columns rows highlights bottom CTA and sticky keyboard scroll',async({page})=>{await page.setViewportSize({width:320,height:1000});await page.goto(url('comparison'));await expect(page.locator('thead th[scope=col]')).toHaveCount(4);await expect(page.locator('tbody th[scope=row]')).toHaveCount(6);await expect(page.locator('tbody tr').last()).toHaveClass('cta-row');await expect(page.locator('.advantage-label')).toHaveCount(3);await expect(page.locator('table')).toHaveAttribute('data-vocabulary','commerce-comparison');const box=page.locator('.table-scroll');expect(await box.evaluate(e=>e.scrollWidth>e.clientWidth)).toBe(true);const before=await page.locator('thead th').first().boundingBox();await box.focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(150);expect(await box.evaluate(e=>e.scrollLeft)).toBeGreaterThan(0);const after=await page.locator('thead th').first().boundingBox();expect(Math.abs(after!.x-before!.x)).toBeLessThan(2);await page.locator('.cta').last().focus();await page.keyboard.press('Enter');await expect(page.locator('#event-status')).toContainText('ローカルイベント');});
test('AC-B altered canonical fixture reaches all five renders and JSON-LD',async()=>{const changed=structuredClone(catalog);changed.products[0].name='変更した架空商品';changed.products[0].price=12345;changed.products[0].rating=3.1;for(const f of surfaces){const html=renderPage(f.id,changed);expect(html).toContain('変更した架空商品');expect(html).toContain('data-price="12345"');expect(html).toContain('data-rating="3.1"');const json=structured(changed,f.id)['@graph'].find(x=>x.sku==='light-a');expect(json.name).toBe(changed.products[0].name);expect(json.offers.price).toBe(12345);}});
test('AC-B route branching needs complete merchant policies and known destination',async()=>{for(const missing of ['shipping','returns']){const changed=structuredClone(catalog);delete changed.products[2][missing];expect(()=>structured(changed,'card')).toThrow('Merchant policies required');}const unknown=structuredClone(catalog);unknown.products[0].linkType='unknown';expect(()=>renderPage('card',unknown)).toThrow('Unsupported link type');const noGoal=structuredClone(catalog);noGoal.products[0].goalCvId='';expect(()=>renderPage('card',noGoal)).toThrow('Invalid product');const graph=structured(catalog,'review')['@graph'];for(const p of catalog.products){const node=graph.find(x=>x.sku===p.id);expect(node.review.reviewBody).toBe(p.review);expect(node.review.positiveNotes.itemListElement.map(x=>x.name)).toEqual(p.pros);expect(node.review.negativeNotes.itemListElement.map(x=>x.name)).toEqual(p.cons);}const merchant=graph.find(x=>x.sku==='light-c');expect(merchant.offers.shippingDetails.shippingRate.value).toBe(0);expect(merchant.offers.hasMerchantReturnPolicy.merchantReturnDays).toBe(14);});
for(const kind of ['card','comparison'])test(`AC-A ${kind} keyboard and 200 percent root text keep document within viewport`,async({page})=>{await page.setViewportSize({width:390,height:1000});await page.goto(url(kind));await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');await page.addStyleTag({content:':root{font-size:32px}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const cta=page.locator('.cta').first();await cta.focus();await page.keyboard.press('Enter');await expect(page.locator('#demo-destination')).toBeFocused();const sizes=await page.locator('.cta-block').first().evaluate(e=>[getComputedStyle(e.querySelector('.cta')!).fontSize,getComputedStyle(e.querySelector('.condition')!).fontSize]);expect(sizes[0]).toBe(sizes[1]);});
