<?php
/**
 * Title: 記事キット
 * Slug: helix-wt/article-kit
 * Categories: helix-wt
 * Description: リード・目次・囲み・比較表・商品カード・レビュー・CTA
 */
$u = get_theme_file_uri( "assets/img" );
?>
<!-- wp:paragraph {"className":"wt-lead"} --><p class="wt-lead"><?php esc_html_e( '法人向けのクラウド会計を 3 社比較しました。月額・仕訳の自動化・税理士連携で選ぶなら、結論は「従業員 10 名までなら B、それ以上なら A」です。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:html --><details class="wt-toc" open><summary><?php esc_html_e( 'この記事の内容', 'helix-wt' ); ?></summary><ol><li><a href="#h-1"><?php esc_html_e( '比較の前提', 'helix-wt' ); ?></a></li><li><a href="#h-2"><?php esc_html_e( '3 社の比較表', 'helix-wt' ); ?></a></li><li><a href="#h-3"><?php esc_html_e( '各サービスの評価', 'helix-wt' ); ?></a></li><li><a href="#h-4"><?php esc_html_e( '結論と選び方', 'helix-wt' ); ?></a></li></ol></details><!-- /wp:html -->
<!-- wp:heading {"anchor":"h-1"} --><h2 class="wp-block-heading" id="h-1"><?php esc_html_e( '比較の前提', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:paragraph --><p><?php esc_html_e( '対象は従業員 30 名以下の法人。評価軸は月額、銀行連携の対応数、仕訳の自動化精度、税理士との共有のしやすさ、サポートの 5 点です。価格は 2026 年 8 月時点の公式サイトの表示に基づきます。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:group {"className":"is-style-wt-point","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-point"><!-- wp:paragraph {"style":{"typography":{"fontWeight":"700"}}} --><p style="font-weight:700"><?php esc_html_e( 'ポイント', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"s"} --><p class="has-s-font-size"><?php esc_html_e( '月額の差より、仕訳の自動化で減る作業時間のほうが年間コストに効きます。時給換算で比べてください。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:heading {"anchor":"h-2"} --><h2 class="wp-block-heading" id="h-2"><?php esc_html_e( '3 社の比較表', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:table {"className":"is-style-wt-compare"} --><figure class="wp-block-table is-style-wt-compare"><table><thead><tr><th></th><th><?php esc_html_e( 'サービス A', 'helix-wt' ); ?></th><th><?php esc_html_e( 'サービス B', 'helix-wt' ); ?></th><th><?php esc_html_e( 'サービス C', 'helix-wt' ); ?></th></tr></thead><tbody><tr><td><?php esc_html_e( '月額（税込）', 'helix-wt' ); ?></td><td><?php esc_html_e( '3,278 円', 'helix-wt' ); ?></td><td><?php esc_html_e( '2,178 円', 'helix-wt' ); ?></td><td><?php esc_html_e( '2,948 円', 'helix-wt' ); ?></td></tr><tr><td><?php esc_html_e( '銀行連携', 'helix-wt' ); ?></td><td><?php esc_html_e( '3,600 以上', 'helix-wt' ); ?></td><td><?php esc_html_e( '2,400 以上', 'helix-wt' ); ?></td><td><?php esc_html_e( '3,100 以上', 'helix-wt' ); ?></td></tr><tr><td><?php esc_html_e( '仕訳の自動提案', 'helix-wt' ); ?></td><td><?php esc_html_e( '◎ 学習あり', 'helix-wt' ); ?></td><td>○</td><td>○</td></tr><tr><td><?php esc_html_e( '税理士共有', 'helix-wt' ); ?></td><td><?php esc_html_e( '◎ 招待無料', 'helix-wt' ); ?></td><td><?php esc_html_e( '○ 1 名まで', 'helix-wt' ); ?></td><td><?php esc_html_e( '△ 有料', 'helix-wt' ); ?></td></tr><tr><td><?php esc_html_e( 'サポート', 'helix-wt' ); ?></td><td><?php esc_html_e( 'チャット・電話', 'helix-wt' ); ?></td><td><?php esc_html_e( 'チャット', 'helix-wt' ); ?></td><td><?php esc_html_e( 'メール', 'helix-wt' ); ?></td></tr></tbody></table><figcaption><?php esc_html_e( '2026 年 8 月時点、各社公式サイトの表示より。', 'helix-wt' ); ?></figcaption></figure><!-- /wp:table -->
<!-- wp:heading {"anchor":"h-3"} --><h2 class="wp-block-heading" id="h-3"><?php esc_html_e( '各サービスの評価', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'サービス A：自動化の精度が高い', 'helix-wt' ); ?></h3><!-- /wp:heading -->
<!-- wp:group {"className":"is-style-wt-card wt-product","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-card wt-product"><!-- wp:group {"className":"wt-photo","style":{"dimensions":{"aspectRatio":"1"}},"layout":{"type":"default"}} --><div class="wp-block-group wt-photo" style="aspect-ratio:1"><img src="<?php echo esc_url( $u ); ?>/product-a.png" alt=""></div><!-- /wp:group --><!-- wp:group {"layout":{"type":"default"},"style":{"spacing":{"blockGap":"0.5rem"}}} --><div class="wp-block-group"><!-- wp:paragraph --><p><span class="wt-badge"><?php esc_html_e( '総合 1 位', 'helix-wt' ); ?></span><span class="wt-stars">★★★★★</span> <strong>4.6</strong></p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"typography":{"fontWeight":"700"}}} --><p style="font-weight:700"><?php esc_html_e( 'サービス A スタンダードプラン', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"s","textColor":"mute"} --><p class="has-mute-color has-text-color has-s-font-size"><?php esc_html_e( '月額 3,278 円 ・ 初月無料 ・ 税理士招待無料', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"cta","textColor":"cta-contrast"} --><div class="wp-block-button"><a class="wp-block-button__link has-cta-contrast-color has-cta-background-color has-text-color has-background wp-element-button" href="#" rel="sponsored nofollow"><?php esc_html_e( '公式サイトで無料で試す', 'helix-wt' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:paragraph --><p><?php esc_html_e( '3 か月使った範囲では、同じ取引先の仕訳は 2 回目からほぼ自動で入りました。銀行連携の数も最多で、地方銀行の口座もそのまま使えます。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:list {"className":"is-style-wt-check"} --><ul class="wp-block-list is-style-wt-check"><li><?php esc_html_e( '仕訳の学習が速く、月末作業が半分になった', 'helix-wt' ); ?></li><li><?php esc_html_e( '税理士を無料で招待でき、共有がメールに頼らない', 'helix-wt' ); ?></li><li><?php esc_html_e( '電話サポートは平日のみ', 'helix-wt' ); ?></li></ul><!-- /wp:list -->
<!-- wp:group {"className":"is-style-wt-warn","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-warn"><!-- wp:paragraph {"fontSize":"s"} --><p class="has-s-font-size"><?php esc_html_e( '本記事にはプロモーションが含まれます。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'サービス B：小規模なら最安', 'helix-wt' ); ?></h3><!-- /wp:heading -->
<!-- wp:paragraph --><p><?php esc_html_e( '月額は最安で、従業員 10 名までの会社なら機能も過不足がありません。銀行連携は少なめですが、主要行はカバーしています。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:quote --><blockquote class="wp-block-quote"><p><?php esc_html_e( '「請求書と仕訳が同じ画面で完結するので、外部の税理士とのやり取りが月 1 回で済むようになった」', 'helix-wt' ); ?></p><cite><?php esc_html_e( '利用 2 年目・従業員 6 名の会社', 'helix-wt' ); ?></cite></blockquote><!-- /wp:quote -->
<!-- wp:heading {"anchor":"h-4"} --><h2 class="wp-block-heading" id="h-4"><?php esc_html_e( '結論と選び方', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:group {"className":"is-style-wt-note","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-note"><!-- wp:list --><ul class="wp-block-list"><li><?php esc_html_e( '従業員 10 名まで、コスト最優先 → サービス B', 'helix-wt' ); ?></li><li><?php esc_html_e( '取引数が多い、税理士と密に共有 → サービス A', 'helix-wt' ); ?></li><li><?php esc_html_e( 'メールサポートで十分、既存ツール連携重視 → サービス C', 'helix-wt' ); ?></li></ul><!-- /wp:list --></div><!-- /wp:group -->
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"cta","textColor":"cta-contrast"} --><div class="wp-block-button"><a class="wp-block-button__link has-cta-contrast-color has-cta-background-color has-text-color has-background wp-element-button" href="#" rel="sponsored nofollow"><?php esc_html_e( 'サービス A を無料で試す', 'helix-wt' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons -->
