<?php
/**
 * Title: 比較記事（試作 03: 昇降デスク 3 製品）
 * Slug: helix-wt/compare-article
 * Categories: helix-wt
 * Description: 比較・アフィリエイト媒体の記事本文の見本。h2 ×5、h3、比較表、メリデメ、評価バー、商品カード束、FAQ。架空の製品名・価格
 */
$u = get_theme_file_uri( 'assets/img' );
?>
<!-- wp:paragraph {"className":"wt-lead"} --><p class="wt-lead"><?php esc_html_e( '在宅ワーク向けの電動昇降デスク 3 製品を、同じ部屋・同じ 2 週間で使い比べました。結論は「予算 6 万円ならリフトワン L1、4 万円以下ならスタンド・ライト S2、天板 160cm 以上が必要ならフレックス・プロ F3」です。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:group {"className":"is-style-wt-band-title","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-band-title"><!-- wp:paragraph --><p><?php esc_html_e( 'この記事でわかること', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-check"} --><ul class="wp-block-list is-style-wt-check"><li><?php esc_html_e( '3 製品の価格・昇降範囲・静音性の違い', 'helix-wt' ); ?></li><li><?php esc_html_e( '部屋の広さと予算別のおすすめ', 'helix-wt' ); ?></li><li><?php esc_html_e( '買ってから後悔しやすい 3 つの落とし穴', 'helix-wt' ); ?></li></ul><!-- /wp:list --></div><!-- /wp:group -->

<!-- wp:heading {"className":"is-style-wt-2tone"} --><h2 class="wp-block-heading is-style-wt-2tone"><?php esc_html_e( '比較の前提と評価軸', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:paragraph {"className":"wt-sub"} --><p class="wt-sub"><?php esc_html_e( '価格は 2026 年 8 月時点の各社公式サイトの表示（税込）。セール価格は含めていません。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:paragraph --><p><?php esc_html_e( '対象は 6〜8 畳の部屋で 1 日 6 時間以上 PC 作業をする人。3 製品を同じ位置に置き、同じ椅子・同じモニターアームで 2 週間ずつ使いました。評価軸は次の 5 点です。椅子との高さ合わせは', 'helix-wt' ); ?><a href="/desk-height-guide/"><?php esc_html_e( '身長別の目安表', 'helix-wt' ); ?></a><?php esc_html_e( 'を先に確認してください。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"is-style-wt-bar-thin"} --><h3 class="wp-block-heading is-style-wt-bar-thin"><?php esc_html_e( '評価軸 5 点', 'helix-wt' ); ?></h3><!-- /wp:heading -->
<!-- wp:list {"className":"is-style-wt-badge-list"} --><ol class="wp-block-list is-style-wt-badge-list"><li><strong><?php esc_html_e( '昇降範囲', 'helix-wt' ); ?></strong> <?php esc_html_e( '— 座り姿勢と立ち姿勢の両方で肘が 90 度になるか', 'helix-wt' ); ?></li><li><strong><?php esc_html_e( '静音性', 'helix-wt' ); ?></strong> <?php esc_html_e( '— 昇降時の音量（1m 離れた位置で測定）', 'helix-wt' ); ?></li><li><strong><?php esc_html_e( '安定性', 'helix-wt' ); ?></strong> <?php esc_html_e( '— 最高位置でのぐらつき、モニター 2 枚での揺れ', 'helix-wt' ); ?></li><li><strong><?php esc_html_e( '価格と保証', 'helix-wt' ); ?></strong> <?php esc_html_e( '— 本体価格、保証年数、返品条件', 'helix-wt' ); ?></li><li><strong><?php esc_html_e( '組み立て', 'helix-wt' ); ?></strong> <?php esc_html_e( '— 1 人で組めるか、所要時間', 'helix-wt' ); ?></li></ol><!-- /wp:list -->
<!-- wp:group {"className":"is-style-wt-tab-title wt-c-point","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-tab-title wt-c-point"><!-- wp:paragraph --><p><?php esc_html_e( 'ポイント', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph --><p><?php esc_html_e( '昇降デスクは「最低高さ」が意外に重要です。身長 160cm 前後の人は座り姿勢で 62cm 以下まで下がらないと、肘が上がって肩がこります。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->

<!-- wp:heading {"className":"is-style-wt-2tone"} --><h2 class="wp-block-heading is-style-wt-2tone"><?php esc_html_e( '3 製品の比較表', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:paragraph --><p><?php esc_html_e( 'まず主要スペックを一覧にします。SP では製品ごとに縦に並びます。◎○△ は文中の基準で付けた筆者の評価です。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:table {"className":"is-style-wt-compare"} --><figure class="wp-block-table is-style-wt-compare"><table><caption><?php esc_html_e( '電動昇降デスク 3 製品の比較（2026 年 8 月時点、税込）', 'helix-wt' ); ?></caption><thead><tr><th><?php esc_html_e( '項目', 'helix-wt' ); ?></th><th><?php esc_html_e( 'リフトワン L1', 'helix-wt' ); ?></th><th><?php esc_html_e( 'スタンド・ライト S2', 'helix-wt' ); ?></th><th><?php esc_html_e( 'フレックス・プロ F3', 'helix-wt' ); ?></th></tr></thead><tbody><tr><td><?php esc_html_e( '価格', 'helix-wt' ); ?></td><td class="wt-num"><?php esc_html_e( '59,800 円', 'helix-wt' ); ?></td><td class="wt-num"><?php esc_html_e( '39,800 円', 'helix-wt' ); ?></td><td class="wt-num"><?php esc_html_e( '84,800 円', 'helix-wt' ); ?></td></tr><tr><td><?php esc_html_e( '昇降範囲', 'helix-wt' ); ?></td><td>62〜127 cm</td><td>71〜118 cm</td><td>60〜125 cm</td></tr><tr><td><?php esc_html_e( '静音性（昇降時）', 'helix-wt' ); ?></td><td><span class="wt-mark">◎</span> <?php esc_html_e( '42 dB（静か）', 'helix-wt' ); ?></td><td><span class="wt-mark">○</span> 48 dB</td><td><span class="wt-mark">◎</span> <?php esc_html_e( '41 dB（静か）', 'helix-wt' ); ?></td></tr><tr><td><?php esc_html_e( '耐荷重', 'helix-wt' ); ?></td><td class="wt-num">100 kg</td><td class="wt-num">70 kg</td><td class="wt-num">125 kg</td></tr><tr><td><?php esc_html_e( '天板サイズ', 'helix-wt' ); ?></td><td>120×60 / 140×70</td><td>120×60</td><td>140×70 / 160×80 / 180×80</td></tr><tr><td><?php esc_html_e( 'メモリー', 'helix-wt' ); ?></td><td><?php esc_html_e( '4 件', 'helix-wt' ); ?></td><td><?php esc_html_e( 'なし', 'helix-wt' ); ?></td><td><?php esc_html_e( '4 件 + アプリ', 'helix-wt' ); ?></td></tr><tr><td><?php esc_html_e( '保証・返品', 'helix-wt' ); ?></td><td><?php esc_html_e( '5 年・30 日', 'helix-wt' ); ?></td><td><?php esc_html_e( '2 年・14 日', 'helix-wt' ); ?></td><td><?php esc_html_e( '7 年・30 日', 'helix-wt' ); ?></td></tr><tr><td><?php esc_html_e( '組み立て（1 人）', 'helix-wt' ); ?></td><td><?php esc_html_e( '約 40 分', 'helix-wt' ); ?></td><td><?php esc_html_e( '約 30 分', 'helix-wt' ); ?></td><td><?php esc_html_e( '約 60 分（重い）', 'helix-wt' ); ?></td></tr></tbody></table><figcaption class="wp-element-caption"><?php esc_html_e( '◎ = 基準を上回る、○ = 基準どおり、△ = 基準を下回る。dB は 1m の位置で計測した筆者の実測。', 'helix-wt' ); ?></figcaption></figure><!-- /wp:table -->
<!-- wp:group {"className":"is-style-wt-tinted wt-c-note","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-tinted wt-c-note"><!-- wp:paragraph {"fontSize":"s"} --><p class="has-s-font-size"><?php esc_html_e( '補足: 昇降範囲は天板の厚みを含む「床から天板上面まで」。キャスターを付けると各値に +5cm 程度加わります。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"is-style-wt-dashed","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-dashed"><!-- wp:paragraph {"style":{"typography":{"fontWeight":"700"}}} --><p style="font-weight:700"><?php esc_html_e( '一時的な注記', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"s"} --><p class="has-s-font-size"><?php esc_html_e( '表の価格は撮影時点のもので、セールや在庫状況により変動します。購入前に各社公式サイトで最新価格をご確認ください。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->

<!-- wp:heading {"className":"is-style-wt-2tone"} --><h2 class="wp-block-heading is-style-wt-2tone"><?php esc_html_e( '各製品のレビュー', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:heading {"level":3,"className":"is-style-wt-bar-thin"} --><h3 class="wp-block-heading is-style-wt-bar-thin"><?php esc_html_e( 'リフトワン L1：総合 1 位。静かで低い位置まで下がる', 'helix-wt' ); ?></h3><!-- /wp:heading -->
<!-- wp:pattern {"slug":"helix-wt/product-bundle"} /-->
<!-- wp:paragraph --><p><?php esc_html_e( '最低 62cm まで下がるので、身長 158cm の筆者でも座り姿勢で肘が 90 度になります。昇降音は 3 製品で 2 番目に静かで、オンライン会議中に動かしても相手に気づかれませんでした。メモリー 4 件はボタン 1 回で移動し、動作中に手を離しても止まりません（安全停止は障害物を検知したときのみ）。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:html --><div class="wt-rate"><span><?php esc_html_e( '昇降範囲', 'helix-wt' ); ?></span><i style="--v:94%"></i><b>4.7</b></div><div class="wt-rate"><span><?php esc_html_e( '静音性', 'helix-wt' ); ?></span><i style="--v:90%"></i><b>4.5</b></div><div class="wt-rate"><span><?php esc_html_e( '安定性', 'helix-wt' ); ?></span><i style="--v:88%"></i><b>4.4</b></div><div class="wt-rate"><span><?php esc_html_e( '価格・保証', 'helix-wt' ); ?></span><i style="--v:84%"></i><b>4.2</b></div><div class="wt-rate"><span><?php esc_html_e( '組み立て', 'helix-wt' ); ?></span><i style="--v:80%"></i><b>4.0</b></div><!-- /wp:html -->
<!-- wp:columns {"className":"wt-prosc"} --><div class="wp-block-columns wt-prosc"><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-label-title wt-c-ok","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-label-title wt-c-ok"><!-- wp:paragraph --><p><?php esc_html_e( 'メリット', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-pros"} --><ul class="wp-block-list is-style-wt-pros"><li><?php esc_html_e( '62cm まで下がる（3 製品で 2 番目）', 'helix-wt' ); ?></li><li><?php esc_html_e( '昇降が静か、会議中でも動かせる', 'helix-wt' ); ?></li><li><?php esc_html_e( '5 年保証・30 日返品', 'helix-wt' ); ?></li></ul><!-- /wp:list --></div><!-- /wp:group --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-label-title wt-c-warn","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-label-title wt-c-warn"><!-- wp:paragraph --><p><?php esc_html_e( 'デメリット', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-cons"} --><ul class="wp-block-list is-style-wt-cons"><li><?php esc_html_e( '天板は 2 サイズのみ、160cm 幅がない', 'helix-wt' ); ?></li><li><?php esc_html_e( '最高位置でモニター 2 枚だと少し揺れる', 'helix-wt' ); ?></li></ul><!-- /wp:list --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns -->

<!-- wp:heading {"level":3,"className":"is-style-wt-bar-thin"} --><h3 class="wp-block-heading is-style-wt-bar-thin"><?php esc_html_e( 'スタンド・ライト S2：4 万円以下ならこれ。ただし最低高さに注意', 'helix-wt' ); ?></h3><!-- /wp:heading -->
<!-- wp:paragraph --><p><?php esc_html_e( '価格は最安で、組み立ても 30 分で終わります。昇降音は 48dB とやや大きめですが、隣の部屋には聞こえません。最低高さ 71cm は身長 170cm 以上向けで、それ以下の人は足置きが必要になります。メモリーがないので、座る・立つの切り替えのたびにボタンを押し続けることになります。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:html --><div class="wt-rate"><span><?php esc_html_e( '昇降範囲', 'helix-wt' ); ?></span><i style="--v:64%"></i><b>3.2</b></div><div class="wt-rate"><span><?php esc_html_e( '静音性', 'helix-wt' ); ?></span><i style="--v:70%"></i><b>3.5</b></div><div class="wt-rate"><span><?php esc_html_e( '安定性', 'helix-wt' ); ?></span><i style="--v:76%"></i><b>3.8</b></div><div class="wt-rate"><span><?php esc_html_e( '価格・保証', 'helix-wt' ); ?></span><i style="--v:92%"></i><b>4.6</b></div><div class="wt-rate"><span><?php esc_html_e( '組み立て', 'helix-wt' ); ?></span><i style="--v:90%"></i><b>4.5</b></div><!-- /wp:html -->
<!-- wp:quote {"className":"is-style-wt-quote-mark"} --><blockquote class="wp-block-quote is-style-wt-quote-mark"><p><?php esc_html_e( '「最初の 1 台としては十分。ただ、身長 165cm の私は座ると天板が高く、結局フットレストを買い足しました」', 'helix-wt' ); ?></p><cite><?php esc_html_e( '利用 3 か月・在宅勤務の読者アンケートより（架空の回答例）', 'helix-wt' ); ?></cite></blockquote><!-- /wp:quote -->

<!-- wp:heading {"level":3,"className":"is-style-wt-bar-thin"} --><h3 class="wp-block-heading is-style-wt-bar-thin"><?php esc_html_e( 'フレックス・プロ F3：広い天板と最静音。価格と重量が壁', 'helix-wt' ); ?></h3><!-- /wp:heading -->
<!-- wp:paragraph --><p><?php esc_html_e( '180cm 幅の天板を選べる唯一の製品で、モニター 3 枚でも揺れません。昇降音 41dB は最も静か。アプリで立ち時間を記録できますが、使ったのは最初の 3 日だけでした。総重量 48kg で、1 人での組み立ては 60 分かかり、2 階への搬入は 2 人必要です。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:group {"className":"is-style-wt-plain-border wt-c-warn","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-plain-border wt-c-warn"><!-- wp:paragraph {"style":{"typography":{"fontWeight":"700"}}} --><p style="font-weight:700"><?php esc_html_e( '注意', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"s"} --><p class="has-s-font-size"><?php esc_html_e( '180cm 天板は梱包サイズが 190×90cm を超え、エレベーターに入らない建物があります。購入前に搬入経路を確認してください。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"is-style-wt-quote","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-quote"><!-- wp:paragraph --><p><?php esc_html_e( '「重いのが唯一の欠点。でも 180cm の天板でモニター 3 枚を並べられるのはこれだけでした」', 'helix-wt' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:pattern {"slug":"helix-wt/cta-banner"} /-->

<!-- wp:heading {"className":"is-style-wt-2tone"} --><h2 class="wp-block-heading is-style-wt-2tone"><?php esc_html_e( '用途別の選び方', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:paragraph --><p><?php esc_html_e( 'スペックより「部屋・身長・予算」で決めるのが失敗しない順番です。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"is-style-wt-num"} --><h3 class="wp-block-heading is-style-wt-num"><?php esc_html_e( '身長 165cm 以下、または座り時間が長い人', 'helix-wt' ); ?></h3><!-- /wp:heading -->
<!-- wp:paragraph --><p><?php esc_html_e( '最低高さが 62cm 以下の L1 か F3。S2 は足置きが前提になります。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"is-style-wt-num"} --><h3 class="wp-block-heading is-style-wt-num"><?php esc_html_e( '予算 4 万円以下で、まず試したい人', 'helix-wt' ); ?></h3><!-- /wp:heading -->
<!-- wp:paragraph --><p><?php esc_html_e( 'S2。14 日以内なら返品できるので、昇降デスク自体が合うかを確かめる用途に向きます。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"is-style-wt-num"} --><h3 class="wp-block-heading is-style-wt-num"><?php esc_html_e( 'モニター 3 枚以上、天板 160cm 以上が必要な人', 'helix-wt' ); ?></h3><!-- /wp:heading -->
<!-- wp:paragraph --><p><?php esc_html_e( 'F3 のみ。搬入経路と床の耐荷重（48kg + 機材）を先に確認してください。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:group {"className":"is-style-wt-card-shadow","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-card-shadow"><!-- wp:paragraph {"style":{"typography":{"fontWeight":"700"}}} --><p style="font-weight:700"><?php esc_html_e( '結論の早見表', 'helix-wt' ); ?></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-icon-list"} --><ul class="wp-block-list is-style-wt-icon-list"><li><?php esc_html_e( '迷ったら → リフトワン L1（総合 1 位）', 'helix-wt' ); ?></li><li><?php esc_html_e( '予算優先 → スタンド・ライト S2', 'helix-wt' ); ?></li><li><?php esc_html_e( '広い天板・最静音 → フレックス・プロ F3', 'helix-wt' ); ?></li></ul><!-- /wp:list --></div><!-- /wp:group -->
<!-- wp:pattern {"slug":"helix-wt/linkcard"} /-->

<!-- wp:heading {"className":"is-style-wt-2tone"} --><h2 class="wp-block-heading is-style-wt-2tone"><?php esc_html_e( 'よくある質問', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:details --><details class="wp-block-details"><summary><?php esc_html_e( '電動と手動（ガス圧）はどちらがいい？', 'helix-wt' ); ?></summary><!-- wp:paragraph --><p><?php esc_html_e( '1 日に 3 回以上切り替えるなら電動。手動は安いが、モニターアームを載せると重くて上げにくくなります。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details --><details class="wp-block-details"><summary><?php esc_html_e( '賃貸で床は傷まない？', 'helix-wt' ); ?></summary><!-- wp:paragraph --><p><?php esc_html_e( '脚の接地面にフェルトを貼れば問題ありません。キャスター付きは避けたほうが床にやさしいです。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details --><details class="wp-block-details"><summary><?php esc_html_e( '天板だけ自分で用意できる？', 'helix-wt' ); ?></summary><!-- wp:paragraph --><p><?php esc_html_e( 'L1 と F3 は脚のみの販売があります。天板は厚み 25mm 以上、重さは耐荷重の 3 割以内を目安にしてください。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details --><details class="wp-block-details"><summary><?php esc_html_e( '電気代はどのくらい？', 'helix-wt' ); ?></summary><!-- wp:paragraph --><p><?php esc_html_e( '待機電力は 3 製品とも 0.5W 未満。1 日 10 回昇降しても月 10 円程度です。', 'helix-wt' ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"var:preset|spacing|60"}}}} --><p style="margin-top:var(--wp--preset--spacing--60)"><?php esc_html_e( '2 週間ずつ使った結論として、最初の 1 台には', 'helix-wt' ); ?> <strong><?php esc_html_e( 'リフトワン L1', 'helix-wt' ); ?></strong> <?php esc_html_e( 'を勧めます。価格を抑えるなら S2、広さと静音を最優先するなら F3 を選んでください。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
<!-- wp:pattern {"slug":"helix-wt/cta-button"} /-->
