<?php
/**
 * Title: イベント / セミナー / キャンペーンページ（選択可能）
 * Slug: helix-wt/event
 * Categories: helix-wt
 * Description: 2026-09-06 PO 反応 17 回目 WT-EVT-0277「イベントとかが組めるページは？」の Claude 案。hero 4 型・開催情報 4 型・スケジュール 4 型・登壇者 4 型・申込 4 型・受付状態 4 型・地図 3 型・固定導線 3 型・共有 3 型。段8（WT-EVT-0287、台帳 home-event-recapture-v2 主集計 n=40）: 区間セット 4 種（seminar / conference / festival / campaign）・申込 +3（receipt-upload / postcard / messaging-app）・区間 +8（対象者 / 主催 / 賞品 / 対象商品 / 応募の流れ / 審査員 / ギャラリー / カウントダウン。固定ページ用パーツ helix-wt-page/* を転用）。
 *              既定は台帳 research-r17（イベント個別募集ページ 8 件、取得 20 件から page_kind 除外後）の最多型。日時・会場・人物は PoC 用の架空。フォームは送信しない。埋め込み地図・外部チケットサービスへは接続しない（リンク先はダミー）。
 */
$u = get_theme_file_uri( 'assets/img' );
$status = '<span class="wt-event-status wt-event-status--open">' . esc_html__( '受付中', 'helix-wt' ) . '</span><span class="wt-event-status wt-event-status--few-seats">' . esc_html__( '残席わずか', 'helix-wt' ) . '</span><span class="wt-event-status wt-event-status--ended">' . esc_html__( '受付終了', 'helix-wt' ) . '</span>';
$apply_btn = '<a class="wt-lp-cta-action wt-event-apply-link" href="#apply">' . esc_html__( '参加を申し込む', 'helix-wt' ) . '</a>';
$event_state = wt_event_fixture_state();
$event_open = ! $event_state || $event_state['open'];
$event_action = $event_open ? esc_html__( '参加を申し込む', 'helix-wt' ) : esc_html__( '受付状況を確認する', 'helix-wt' );
if ( $event_state ) {
	$status = '<span class="wt-event-status" data-wt-event-state="' . esc_attr( $event_state['state'] ) . '">' . esc_html( $event_state['label'] ) . '</span>';
	$apply_btn = '<a class="wt-lp-cta-action wt-event-apply-link" href="#apply">' . esc_html( $event_action ) . '</a>';
}
?>
<!-- wp:html -->
<div class="wt-event-hero-slot" id="event-hero">
<section class="wt-event-hero wt-event-hero--photo-overlay" data-wt-scrim aria-labelledby="event-hero-photo-title"><img class="wt-event-hero__bg" src="<?php echo esc_url( $u ); ?>/media-pickup-2.jpg" alt="" width="1440" height="810" loading="eager" fetchpriority="high" decoding="async"><div class="wt-event-hero__inner"><?php echo $status; ?><p class="wt-eyebrow">SEMINAR</p><h1 id="event-hero-photo-title"><?php esc_html_e( '中小企業のための業務改善セミナー 2026 秋', 'helix-wt' ); ?></h1><p class="wt-event-hero__meta"><time datetime="2026-10-15T14:00"><?php esc_html_e( '2026 年 10 月 15 日（木）14:00〜16:00', 'helix-wt' ); ?></time><span><?php esc_html_e( 'オンライン + 会場（サンプルホール）', 'helix-wt' ); ?></span></p><?php echo $apply_btn; ?></div></section>
<section class="wt-event-hero wt-event-hero--key-visual" aria-labelledby="event-hero-kv-title"><img class="wt-event-hero__kv" src="<?php echo esc_url( $u ); ?>/media-pickup-3.jpg" alt="" width="1440" height="600" loading="eager" fetchpriority="high" decoding="async"><div class="wt-event-hero__inner"><?php echo $status; ?><p class="wt-eyebrow">SEMINAR</p><h1 id="event-hero-kv-title"><?php esc_html_e( '中小企業のための業務改善セミナー 2026 秋', 'helix-wt' ); ?></h1><p class="wt-event-hero__meta"><time datetime="2026-10-15T14:00"><?php esc_html_e( '2026 年 10 月 15 日（木）14:00〜16:00', 'helix-wt' ); ?></time><span><?php esc_html_e( 'オンライン + 会場（サンプルホール）', 'helix-wt' ); ?></span></p><?php echo $apply_btn; ?></div></section>
<section class="wt-event-hero wt-event-hero--date-place-block" aria-labelledby="event-hero-date-title"><div class="wt-event-hero__inner wt-event-hero__grid"><div class="wt-event-date"><b>10<small>/</small>15</b><span><?php esc_html_e( '2026 年（木）', 'helix-wt' ); ?></span><span>14:00〜16:00</span></div><div><?php echo $status; ?><p class="wt-eyebrow">SEMINAR</p><h1 id="event-hero-date-title"><?php esc_html_e( '中小企業のための業務改善セミナー 2026 秋', 'helix-wt' ); ?></h1><p class="wt-event-hero__meta"><span><i class="wt-i wt-i--s wt-i--pin" aria-hidden="true"></i><?php esc_html_e( 'オンライン + 会場（サンプルホール）', 'helix-wt' ); ?></span><span><i class="wt-i wt-i--s wt-i--user" aria-hidden="true"></i><?php esc_html_e( '定員 50 名・参加無料', 'helix-wt' ); ?></span></p><?php echo $apply_btn; ?></div></div></section>
<section class="wt-event-hero wt-event-hero--text-only" aria-labelledby="event-hero-text-title"><div class="wt-event-hero__inner"><?php echo $status; ?><p class="wt-eyebrow">SEMINAR</p><h1 id="event-hero-text-title"><?php esc_html_e( '中小企業のための業務改善セミナー 2026 秋', 'helix-wt' ); ?></h1><p class="wt-event-hero__lead"><?php esc_html_e( '現場の手戻りを減らす「見える化」の始め方を、3 業種の事例とともに 2 時間で解説します（PoC 用の文言）。', 'helix-wt' ); ?></p><?php echo $apply_btn; ?></div></section>
</div>
<!-- /wp:html -->

<!-- wp:group {"className":"wt-event__sections","layout":{"type":"default"}} -->
<div class="wp-block-group wt-event__sections">
<!-- wp:html -->
<section class="wt-event__section wt-event__section--info" id="info" aria-label="<?php echo esc_attr__( '開催情報', 'helix-wt' ); ?>"><div class="wt-lp-section-inner">
<p class="wt-event-info wt-event-info--inline-text"><b><?php esc_html_e( '日時', 'helix-wt' ); ?></b> <?php esc_html_e( '2026 年 10 月 15 日（木）14:00〜16:00（開場 13:30）／', 'helix-wt' ); ?> <b><?php esc_html_e( '会場', 'helix-wt' ); ?></b> <?php esc_html_e( 'サンプルホール 3F + オンライン配信 ／', 'helix-wt' ); ?> <b><?php esc_html_e( '定員', 'helix-wt' ); ?></b> <?php esc_html_e( '会場 50 名・オンライン 300 名 ／', 'helix-wt' ); ?> <b><?php esc_html_e( '参加費', 'helix-wt' ); ?></b> <?php esc_html_e( '無料（事前申込制）／', 'helix-wt' ); ?> <b><?php esc_html_e( '対象', 'helix-wt' ); ?></b> <?php esc_html_e( '中小企業の経営者・管理部門の方', 'helix-wt' ); ?></p>
<table class="wt-event-info wt-event-info--table"><caption class="screen-reader-text"><?php esc_html_e( '開催情報', 'helix-wt' ); ?></caption><tbody><tr><th scope="row"><?php esc_html_e( '日時', 'helix-wt' ); ?></th><td><?php esc_html_e( '2026 年 10 月 15 日（木）14:00〜16:00（開場 13:30）', 'helix-wt' ); ?></td></tr><tr><th scope="row"><?php esc_html_e( '会場', 'helix-wt' ); ?></th><td><?php esc_html_e( 'サンプルホール 3F + オンライン配信', 'helix-wt' ); ?></td></tr><tr><th scope="row"><?php esc_html_e( '定員', 'helix-wt' ); ?></th><td><?php esc_html_e( '会場 50 名・オンライン 300 名', 'helix-wt' ); ?></td></tr><tr><th scope="row"><?php esc_html_e( '参加費', 'helix-wt' ); ?></th><td><?php esc_html_e( '無料（事前申込制）', 'helix-wt' ); ?></td></tr><tr><th scope="row"><?php esc_html_e( '対象', 'helix-wt' ); ?></th><td><?php esc_html_e( '中小企業の経営者・管理部門の方', 'helix-wt' ); ?></td></tr></tbody></table>
<ul class="wt-event-info wt-event-info--icon-list"><li><i class="wt-i wt-i--l wt-i--calendar" aria-hidden="true"></i><b><?php esc_html_e( '日時', 'helix-wt' ); ?></b><span><?php esc_html_e( '10 月 15 日（木）14:00〜16:00', 'helix-wt' ); ?></span></li><li><i class="wt-i wt-i--l wt-i--pin" aria-hidden="true"></i><b><?php esc_html_e( '会場', 'helix-wt' ); ?></b><span><?php esc_html_e( 'サンプルホール 3F + オンライン', 'helix-wt' ); ?></span></li><li><i class="wt-i wt-i--l wt-i--user" aria-hidden="true"></i><b><?php esc_html_e( '定員', 'helix-wt' ); ?></b><span><?php esc_html_e( '会場 50 名・オンライン 300 名', 'helix-wt' ); ?></span></li><li><i class="wt-i wt-i--l wt-i--tag" aria-hidden="true"></i><b><?php esc_html_e( '参加費', 'helix-wt' ); ?></b><span><?php esc_html_e( '無料（事前申込制）', 'helix-wt' ); ?></span></li></ul>
</div></section>

<section class="wt-event__section wt-event__section--overview" id="overview" aria-labelledby="event-overview-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">OVERVIEW</p><h2 id="event-overview-title"><?php esc_html_e( 'このセミナーについて', 'helix-wt' ); ?></h2><p><?php esc_html_e( '日報・申請・記録がばらばらで、集計に時間がかかる。そんな現場で「見える化」をどこから始めるかを、製造・士業・医療の 3 つの事例で解説します。翌日から使えるチェックリストを配布します（PoC 用の文言）。', 'helix-wt' ); ?></p>
<ul class="wt-event-highlights"><li><i class="wt-i wt-i--l wt-i--lightbulb" aria-hidden="true"></i><b><?php esc_html_e( '改善の順番が分かる', 'helix-wt' ); ?></b><span><?php esc_html_e( '効果が出やすい順に 3 段階で整理', 'helix-wt' ); ?></span></li><li><i class="wt-i wt-i--l wt-i--file" aria-hidden="true"></i><b><?php esc_html_e( 'チェックリスト配布', 'helix-wt' ); ?></b><span><?php esc_html_e( '翌日から現場で使える 12 項目', 'helix-wt' ); ?></span></li><li><i class="wt-i wt-i--l wt-i--user" aria-hidden="true"></i><b><?php esc_html_e( '個別相談つき', 'helix-wt' ); ?></b><span><?php esc_html_e( '終了後 30 分・希望者のみ', 'helix-wt' ); ?></span></li></ul></div></section>

<section class="wt-event__section wt-event__section--schedule" id="schedule" aria-labelledby="event-schedule-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">SCHEDULE</p><h2 id="event-schedule-title"><?php esc_html_e( 'タイムテーブル', 'helix-wt' ); ?></h2>
<table class="wt-event-schedule wt-event-schedule--table"><caption class="screen-reader-text"><?php esc_html_e( 'タイムテーブル', 'helix-wt' ); ?></caption><thead><tr><th scope="col"><?php esc_html_e( '時間', 'helix-wt' ); ?></th><th scope="col"><?php esc_html_e( '内容', 'helix-wt' ); ?></th><th scope="col"><?php esc_html_e( '登壇', 'helix-wt' ); ?></th></tr></thead><tbody><tr><td>14:00</td><td><?php esc_html_e( '開会・趣旨説明', 'helix-wt' ); ?></td><td><?php esc_html_e( '事務局', 'helix-wt' ); ?></td></tr><tr><td>14:10</td><td><?php esc_html_e( '見える化の始め方 3 段階', 'helix-wt' ); ?></td><td><?php esc_html_e( '登壇者 A', 'helix-wt' ); ?></td></tr><tr><td>14:50</td><td><?php esc_html_e( '事例: 製造・士業・医療', 'helix-wt' ); ?></td><td><?php esc_html_e( '登壇者 B', 'helix-wt' ); ?></td></tr><tr><td>15:30</td><td><?php esc_html_e( '質疑応答', 'helix-wt' ); ?></td><td><?php esc_html_e( '全員', 'helix-wt' ); ?></td></tr><tr><td>16:00</td><td><?php esc_html_e( '閉会・個別相談（希望者）', 'helix-wt' ); ?></td><td><?php esc_html_e( '事務局', 'helix-wt' ); ?></td></tr></tbody></table>
<ol class="wt-event-schedule wt-event-schedule--timeline"><li><time>14:00</time><div><b><?php esc_html_e( '開会・趣旨説明', 'helix-wt' ); ?></b><span><?php esc_html_e( '事務局', 'helix-wt' ); ?></span></div></li><li><time>14:10</time><div><b><?php esc_html_e( '見える化の始め方 3 段階', 'helix-wt' ); ?></b><span><?php esc_html_e( '登壇者 A', 'helix-wt' ); ?></span></div></li><li><time>14:50</time><div><b><?php esc_html_e( '事例: 製造・士業・医療', 'helix-wt' ); ?></b><span><?php esc_html_e( '登壇者 B', 'helix-wt' ); ?></span></div></li><li><time>15:30</time><div><b><?php esc_html_e( '質疑応答', 'helix-wt' ); ?></b><span><?php esc_html_e( '全員', 'helix-wt' ); ?></span></div></li><li><time>16:00</time><div><b><?php esc_html_e( '閉会・個別相談（希望者）', 'helix-wt' ); ?></b><span><?php esc_html_e( '事務局', 'helix-wt' ); ?></span></div></li></ol>
<div class="wt-event-schedule wt-event-schedule--accordion"><details open><summary><time>14:00</time> <?php esc_html_e( '開会・趣旨説明', 'helix-wt' ); ?></summary><p><?php esc_html_e( '事務局より本日の流れと資料の案内。', 'helix-wt' ); ?></p></details><details><summary><time>14:10</time> <?php esc_html_e( '見える化の始め方 3 段階', 'helix-wt' ); ?></summary><p><?php esc_html_e( '効果が出やすい順に「記録 → 集計 → 判断」の 3 段階で整理します。', 'helix-wt' ); ?></p></details><details><summary><time>14:50</time> <?php esc_html_e( '事例: 製造・士業・医療', 'helix-wt' ); ?></summary><p><?php esc_html_e( '3 業種の導入前後の数字を比べます。', 'helix-wt' ); ?></p></details><details><summary><time>15:30</time> <?php esc_html_e( '質疑応答', 'helix-wt' ); ?></summary><p><?php esc_html_e( '事前質問と会場からの質問に答えます。', 'helix-wt' ); ?></p></details></div>
</div></section>

<section class="wt-event__section wt-event__section--speakers" id="speakers" aria-labelledby="event-speakers-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">SPEAKERS</p><h2 id="event-speakers-title"><?php esc_html_e( '登壇者', 'helix-wt' ); ?></h2>
<ul class="wt-event-speakers wt-event-speakers--cards-photo"><li><img src="<?php echo esc_url( $u ); ?>/avatar.png" alt="" width="160" height="160" loading="lazy" decoding="async"><b><?php esc_html_e( '登壇者 A', 'helix-wt' ); ?></b><small><?php esc_html_e( '業務改善コンサルタント', 'helix-wt' ); ?></small><span><?php esc_html_e( '製造業を中心に 120 社の現場改善を支援（PoC 用の架空の経歴）。', 'helix-wt' ); ?></span></li><li><img src="<?php echo esc_url( $u ); ?>/avatar.png" alt="" width="160" height="160" loading="lazy" decoding="async"><b><?php esc_html_e( '登壇者 B', 'helix-wt' ); ?></b><small><?php esc_html_e( '士業事務所 代表', 'helix-wt' ); ?></small><span><?php esc_html_e( '問い合わせ対応の 1 本化で返信を翌営業日以内に。', 'helix-wt' ); ?></span></li><li><img src="<?php echo esc_url( $u ); ?>/avatar.png" alt="" width="160" height="160" loading="lazy" decoding="async"><b><?php esc_html_e( '登壇者 C', 'helix-wt' ); ?></b><small><?php esc_html_e( '医療法人 事務長', 'helix-wt' ); ?></small><span><?php esc_html_e( '予約と問診の流れを整え、待ち時間を 2 割短縮。', 'helix-wt' ); ?></span></li></ul>
<ul class="wt-event-speakers wt-event-speakers--list"><li><b><?php esc_html_e( '登壇者 A', 'helix-wt' ); ?></b><span><?php esc_html_e( '業務改善コンサルタント', 'helix-wt' ); ?></span></li><li><b><?php esc_html_e( '登壇者 B', 'helix-wt' ); ?></b><span><?php esc_html_e( '士業事務所 代表', 'helix-wt' ); ?></span></li><li><b><?php esc_html_e( '登壇者 C', 'helix-wt' ); ?></b><span><?php esc_html_e( '医療法人 事務長', 'helix-wt' ); ?></span></li></ul>
<div class="wt-event-speakers wt-event-speakers--single-profile"><img src="<?php echo esc_url( $u ); ?>/avatar.png" alt="" width="200" height="200" loading="lazy" decoding="async"><div><b><?php esc_html_e( '登壇者 A', 'helix-wt' ); ?></b><small><?php esc_html_e( '業務改善コンサルタント', 'helix-wt' ); ?></small><p><?php esc_html_e( '製造業を中心に 120 社の現場改善を支援。「記録 → 集計 → 判断」の 3 段階で、担当が変わっても回る仕組みづくりを専門とする（PoC 用の架空の経歴）。', 'helix-wt' ); ?></p></div></div>
</div></section>

<section class="wt-event__section wt-event__section--tickets" id="tickets" aria-labelledby="event-tickets-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">TICKETS</p><h2 id="event-tickets-title"><?php esc_html_e( '参加区分', 'helix-wt' ); ?></h2>
<ul class="wt-event-tickets"><li><b><?php esc_html_e( '会場参加', 'helix-wt' ); ?></b><p class="wt-event-tickets__price"><?php esc_html_e( '無料', 'helix-wt' ); ?></p><span><?php esc_html_e( '定員 50 名・資料付き・個別相談あり', 'helix-wt' ); ?></span></li><li class="is-featured"><b><?php esc_html_e( 'オンライン参加', 'helix-wt' ); ?></b><p class="wt-event-tickets__price"><?php esc_html_e( '無料', 'helix-wt' ); ?></p><span><?php esc_html_e( '定員 300 名・後日録画を 1 週間視聴可', 'helix-wt' ); ?></span></li><li><b><?php esc_html_e( '録画のみ', 'helix-wt' ); ?></b><p class="wt-event-tickets__price"><?php esc_html_e( '無料', 'helix-wt' ); ?></p><span><?php esc_html_e( '当日参加できない方向け・質疑は不可', 'helix-wt' ); ?></span></li></ul></div></section>

<section class="wt-event__section wt-event__section--apply" id="apply" aria-labelledby="event-apply-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">APPLY</p><h2 id="event-apply-title"><?php esc_html_e( '参加申込', 'helix-wt' ); ?></h2>
<?php if ( ! $event_open ) : ?>
<div class="wt-event-availability" role="status"><h3><?php echo esc_html( $event_state['label'] ); ?></h3><p><?php esc_html_e( '現在は申込を受け付けていません。受付状況をご確認ください。', 'helix-wt' ); ?></p><a href="#info"><?php esc_html_e( '開催情報を確認する', 'helix-wt' ); ?></a></div>
<?php else : ?>
<form class="wt-event-apply wt-event-apply--inline-form wt-lp-form-inline" action="#apply" method="get" data-wt-poc-form="no-submit"><div class="wt-lp-form__grid"><div><label for="ev-name"><?php esc_html_e( 'お名前', 'helix-wt' ); ?></label><input id="ev-name" name="name" type="text" autocomplete="name" required></div><div><label for="ev-company"><?php esc_html_e( '会社名', 'helix-wt' ); ?></label><input id="ev-company" name="company" type="text" autocomplete="organization"></div><div><label for="ev-email"><?php esc_html_e( 'メールアドレス', 'helix-wt' ); ?></label><input id="ev-email" name="email" type="email" autocomplete="email" required></div><div><label for="ev-type"><?php esc_html_e( '参加区分', 'helix-wt' ); ?></label><select id="ev-type" name="type"><option><?php esc_html_e( '会場参加', 'helix-wt' ); ?></option><option><?php esc_html_e( 'オンライン参加', 'helix-wt' ); ?></option><option><?php esc_html_e( '録画のみ', 'helix-wt' ); ?></option></select></div></div><label class="wt-event-apply__consent"><input type="checkbox" name="consent" required> <?php esc_html_e( '個人情報の取り扱いに同意する', 'helix-wt' ); ?></label><button class="wt-lp-cta-action" type="button" aria-describedby="ev-note"><?php esc_html_e( '申し込む', 'helix-wt' ); ?></button><p id="ev-note" class="wt-lp-form__note"><?php esc_html_e( 'PoC のため送信されません。', 'helix-wt' ); ?></p></form>
<div class="wt-event-apply wt-event-apply--external-form"><p><?php esc_html_e( '申込フォームは別ページで開きます（所要 2 分）。', 'helix-wt' ); ?></p><a class="wt-lp-cta-action" href="#apply" rel="nofollow"><?php esc_html_e( '申込フォームへ進む', 'helix-wt' ); ?> <i class="wt-i wt-i--s wt-i--external" aria-hidden="true"></i></a><p class="wt-lp-form__note"><?php esc_html_e( '遷移先は PoC のためダミーのアンカー。', 'helix-wt' ); ?></p></div>
<div class="wt-event-apply wt-event-apply--ticket-link"><p><?php esc_html_e( 'チケットは外部のチケットサービスで受け付けています。', 'helix-wt' ); ?></p><a class="wt-lp-cta-action" href="#apply" rel="nofollow"><?php esc_html_e( 'チケットサービスで申し込む', 'helix-wt' ); ?> <i class="wt-i wt-i--s wt-i--external" aria-hidden="true"></i></a><p class="wt-lp-form__note"><?php esc_html_e( 'サービス名・遷移先は PoC のため置かない。', 'helix-wt' ); ?></p></div>
<div class="wt-event-apply wt-event-apply--receipt-upload"><ol class="wt-event-apply__steps"><li><i class="wt-i wt-i--l wt-i--cart" aria-hidden="true"></i><b><?php esc_html_e( '買う', 'helix-wt' ); ?></b><span><?php esc_html_e( '対象商品を 1,000 円以上', 'helix-wt' ); ?></span></li><li><i class="wt-i wt-i--l wt-i--edit" aria-hidden="true"></i><b><?php esc_html_e( '撮る', 'helix-wt' ); ?></b><span><?php esc_html_e( 'レシート全体が写るように', 'helix-wt' ); ?></span></li><li><i class="wt-i wt-i--l wt-i--check-circle" aria-hidden="true"></i><b><?php esc_html_e( '送る', 'helix-wt' ); ?></b><span><?php esc_html_e( '下のボタンから画像を送信', 'helix-wt' ); ?></span></li></ol><div class="wt-event-apply__upload" role="group" aria-labelledby="ev-upload-title"><b id="ev-upload-title"><?php esc_html_e( 'レシート画像を選ぶ', 'helix-wt' ); ?></b><p><?php esc_html_e( 'JPEG / PNG、5MB まで。購入日・店名・商品名が読めるもの。', 'helix-wt' ); ?></p><button class="wt-lp-cta-action wt-event-apply-link" type="button" aria-describedby="ev-upload-note"><?php esc_html_e( '画像を選んで応募する', 'helix-wt' ); ?></button><p id="ev-upload-note" class="wt-lp-form__note"><?php esc_html_e( 'PoC のため画像は選択・送信されない（台帳 v2: other:receipt-upload、D で 38%）。', 'helix-wt' ); ?></p></div></div>
<div class="wt-event-apply wt-event-apply--postcard"><div class="wt-event-apply__postcard"><div class="wt-event-apply__addr"><p class="wt-eyebrow"><?php esc_html_e( '宛先', 'helix-wt' ); ?></p><p><b>〒000-0000</b><br><?php esc_html_e( '設定された所在地', 'helix-wt' ); ?><br><?php esc_html_e( 'サンプル株式会社「秋のキャンペーン」係（架空）', 'helix-wt' ); ?></p></div><div><p class="wt-eyebrow"><?php esc_html_e( '必要事項', 'helix-wt' ); ?></p><ol><li><?php esc_html_e( '郵便番号・住所・氏名・電話番号', 'helix-wt' ); ?></li><li><?php esc_html_e( '希望の賞品（A 賞 / B 賞）', 'helix-wt' ); ?></li><li><?php esc_html_e( 'レシート原本（コピー不可）を貼付', 'helix-wt' ); ?></li></ol><p class="wt-lp-form__note"><?php esc_html_e( '当日消印有効。はがき応募（台帳 v2: other:postcard、D で 38%）。web 応募は', 'helix-wt' ); ?> <a class="wt-event-apply-link" href="#apply"><?php esc_html_e( 'フォーム', 'helix-wt' ); ?></a> <?php esc_html_e( 'からも可（PoC のダミー）。', 'helix-wt' ); ?></p></div></div></div>
<div class="wt-event-apply wt-event-apply--messaging-app"><div class="wt-event-apply__app"><div><p><?php esc_html_e( '公式アカウントを友だち追加し、トーク画面からレシート画像を送って応募（台帳 v2: other:messaging-app、D で 25%）。', 'helix-wt' ); ?></p><a class="wt-lp-cta-action wt-event-apply-link" href="#apply" rel="nofollow"><i class="wt-i wt-i--s wt-i--bubble" aria-hidden="true"></i> <?php esc_html_e( '友だち追加して応募', 'helix-wt' ); ?></a><p class="wt-lp-form__note"><?php esc_html_e( 'サービス名・実 URL・QR は PoC のため置かない（ダミー模様）。', 'helix-wt' ); ?></p></div><svg class="wt-event-apply__qr" viewBox="0 0 21 21" role="img" aria-label="<?php echo esc_attr__( 'QR コードのダミー模様（実コードではない）', 'helix-wt' ); ?>" width="120" height="120"><path fill="currentColor" d="M0 0h7v7H0zM14 0h7v7h-7zM0 14h7v7H0zM2 2h3v3H2zM16 2h3v3h-3zM2 16h3v3H2zM9 1h1v2H9zM11 0h1v3h-1zM9 5h3v1H9zM8 8h2v2H8zM11 8h1v1h-1zM13 9h2v1h-2zM16 8h1v3h-1zM18 9h3v1h-3zM9 11h1v3H9zM11 12h3v1h-3zM15 12h1v2h-1zM17 12h2v2h-2zM20 11h1v3h-1zM9 15h2v1H9zM12 15h1v3h-1zM14 16h3v1h-3zM18 15h1v2h-1zM20 16h1v2h-1zM9 18h1v3H9zM11 19h2v2h-2zM14 18h1v3h-1zM16 19h3v1h-3zM20 19h1v2h-1z"/></svg></div></div>
<div class="wt-event-apply wt-event-apply--closed-notice" role="status"><i class="wt-i wt-i--l wt-i--info" aria-hidden="true"></i><div><b><?php esc_html_e( '本イベントの受付は終了しました。', 'helix-wt' ); ?></b><p><?php esc_html_e( '次回開催のご案内はお知らせでお伝えします。', 'helix-wt' ); ?><a href="/"><?php esc_html_e( 'お知らせを見る', 'helix-wt' ); ?></a></p></div></div>
<!-- /wp:html -->
<!-- wp:group {"className":"wt-event-apply wt-event-apply--block-form","layout":{"type":"constrained"}} -->
<div class="wp-block-group wt-event-apply wt-event-apply--block-form"><!-- wp:helix-wt/form {"hideTitle":true} /--></div>
<!-- /wp:group -->
<!-- wp:html -->
<?php endif; ?>
</div></section>

<section class="wt-event__section wt-event__section--access" id="access" aria-labelledby="event-access-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">ACCESS</p><h2 id="event-access-title"><?php esc_html_e( '会場アクセス', 'helix-wt' ); ?></h2>
<div class="wt-event-map wt-event-map--static-image"><img src="<?php echo esc_url( $u ); ?>/lum-light.jpg" alt="<?php echo esc_attr__( '会場周辺の地図（PoC 用のダミー画像。実運用では地図画像を置く）', 'helix-wt' ); ?>" width="1200" height="600" loading="lazy" decoding="async"><address><b><?php esc_html_e( 'サンプルホール 3F', 'helix-wt' ); ?></b><br><?php esc_html_e( '設定された所在地', 'helix-wt' ); ?><br><?php esc_html_e( '最寄り駅から徒歩 5 分', 'helix-wt' ); ?></address></div>
<address class="wt-event-map wt-event-map--text-only"><b><?php esc_html_e( 'サンプルホール 3F', 'helix-wt' ); ?></b><br><?php esc_html_e( '設定された所在地', 'helix-wt' ); ?><br><?php esc_html_e( '最寄り駅から徒歩 5 分（PoC 用の文言）', 'helix-wt' ); ?></address>
<?php echo wt_render_event_map_embed(); ?>
</div></section>

<section class="wt-event__section wt-event__section--faq" id="faq" aria-labelledby="event-faq-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">FAQ</p><h2 id="event-faq-title"><?php esc_html_e( 'よくある質問', 'helix-wt' ); ?></h2><div class="wt-home-faq"><details><summary><?php esc_html_e( '途中参加・途中退出はできますか', 'helix-wt' ); ?></summary><p><?php esc_html_e( 'できます。オンラインは録画を後日視聴できます。', 'helix-wt' ); ?></p></details><details><summary><?php esc_html_e( '資料はもらえますか', 'helix-wt' ); ?></summary><p><?php esc_html_e( '参加者全員に PDF で配布します。', 'helix-wt' ); ?></p></details><details><summary><?php esc_html_e( '同業の参加はできますか', 'helix-wt' ); ?></summary><p><?php esc_html_e( '同業のコンサルティング事業者の参加はお断りする場合があります。', 'helix-wt' ); ?></p></details></div></div></section>

<section class="wt-event__section wt-event__section--sponsors" id="sponsors" aria-labelledby="event-sponsors-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">SPONSORS</p><h2 id="event-sponsors-title"><?php esc_html_e( '協賛・協力', 'helix-wt' ); ?></h2><ul class="wt-lp-logo-row" aria-label="<?php echo esc_attr__( '協賛ロゴ枠', 'helix-wt' ); ?>"><li>LOGO 1</li><li>LOGO 2</li><li>LOGO 3</li><li>LOGO 4</li><li>LOGO 5</li></ul></div></section>

<section class="wt-event__section wt-event__section--past" id="past" aria-labelledby="event-past-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">REPORT</p><h2 id="event-past-title"><?php esc_html_e( '過去の開催', 'helix-wt' ); ?></h2><ul class="wt-home-cards wt-home-cards--cases"><li><a href="#past"><img src="<?php echo esc_url( $u ); ?>/media-pickup-5.jpg" alt="" width="640" height="360" loading="lazy" decoding="async"><small><?php esc_html_e( '2026 年 6 月・参加 180 名', 'helix-wt' ); ?></small><b><?php esc_html_e( '春の業務改善セミナー レポート', 'helix-wt' ); ?></b></a></li><li><a href="#past"><img src="<?php echo esc_url( $u ); ?>/media-pickup-6.jpg" alt="" width="640" height="360" loading="lazy" decoding="async"><small><?php esc_html_e( '2026 年 2 月・参加 140 名', 'helix-wt' ); ?></small><b><?php esc_html_e( '冬の事例共有会 レポート', 'helix-wt' ); ?></b></a></li><li><a href="#past"><img src="<?php echo esc_url( $u ); ?>/media-pickup-1.jpg" alt="" width="640" height="360" loading="lazy" decoding="async"><small><?php esc_html_e( '2025 年 10 月・参加 120 名', 'helix-wt' ); ?></small><b><?php esc_html_e( '秋の業務改善セミナー レポート', 'helix-wt' ); ?></b></a></li></ul></div></section>

<section class="wt-event__section wt-event__section--notes" id="notes" aria-labelledby="event-notes-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">NOTES</p><h2 id="event-notes-title"><?php esc_html_e( '注意事項', 'helix-wt' ); ?></h2><ul class="wt-event-notes"><li><?php esc_html_e( '申込多数の場合は抽選となることがあります。', 'helix-wt' ); ?></li><li><?php esc_html_e( '会場での撮影・録音はご遠慮ください。', 'helix-wt' ); ?></li><li><?php esc_html_e( '内容・登壇者は予告なく変更になる場合があります。', 'helix-wt' ); ?></li></ul><p class="wt-event-organizer"><b><?php esc_html_e( '主催', 'helix-wt' ); ?></b> <?php esc_html_e( 'サンプル株式会社（架空）', 'helix-wt' ); ?>　<b><?php esc_html_e( 'お問い合わせ', 'helix-wt' ); ?></b> <a href="#notes">event@example.invalid</a></p>
<div class="wt-event-share wt-event-share--icons" id="share" aria-label="<?php echo esc_attr__( 'このイベントを共有', 'helix-wt' ); ?>" data-wt-poc-dummy="share-targets"><span><?php esc_html_e( '共有', 'helix-wt' ); ?></span><a class="wt-sns" href="#share" rel="nofollow" aria-label="<?php echo esc_attr__( 'X でポスト', 'helix-wt' ); ?>"><i class="wt-i wt-i--sns-x" aria-hidden="true"></i></a><a class="wt-sns" href="#share" rel="nofollow" aria-label="<?php echo esc_attr__( 'LINE で送る', 'helix-wt' ); ?>"><i class="wt-i wt-i--bubble" aria-hidden="true"></i></a><button type="button" data-wt-share="copy" aria-label="<?php echo esc_attr__( 'リンクをコピー', 'helix-wt' ); ?>">⧉</button></div>
<div class="wt-event-share wt-event-share--add-to-calendar" id="calendar" data-wt-poc-dummy="ics"><a class="wt-lp-cta-action wt-lp-cta-action--secondary" href="#calendar" rel="nofollow"><i class="wt-i wt-i--s wt-i--calendar" aria-hidden="true"></i> <?php esc_html_e( 'カレンダーに追加', 'helix-wt' ); ?></a><p class="wt-lp-form__note"><?php esc_html_e( '実運用では .ics を配布する。PoC ではダミーのアンカー。', 'helix-wt' ); ?></p></div>
</div></section>
<!-- /wp:html -->
<!-- wp:group {"anchor":"audience","className":"wt-event__section wt-event__section--audience","layout":{"type":"default"}} -->
<div class="wp-block-group wt-event__section wt-event__section--audience" id="audience"><!-- wp:pattern {"slug":"helix-wt-page/target-audience"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"organizer","className":"wt-event__section wt-event__section--organizer","layout":{"type":"default"}} -->
<div class="wp-block-group wt-event__section wt-event__section--organizer" id="organizer"><!-- wp:pattern {"slug":"helix-wt-page/organizer"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"prizes","className":"wt-event__section wt-event__section--prizes","layout":{"type":"default"}} -->
<div class="wp-block-group wt-event__section wt-event__section--prizes" id="prizes"><!-- wp:pattern {"slug":"helix-wt-page/prizes"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"products","className":"wt-event__section wt-event__section--products","layout":{"type":"default"}} -->
<div class="wp-block-group wt-event__section wt-event__section--products" id="products"><!-- wp:pattern {"slug":"helix-wt-page/target-products"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"entry","className":"wt-event__section wt-event__section--entry","layout":{"type":"default"}} -->
<div class="wp-block-group wt-event__section wt-event__section--entry" id="entry"><!-- wp:pattern {"slug":"helix-wt-page/entry-steps"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"judges","className":"wt-event__section wt-event__section--judges","layout":{"type":"default"}} -->
<div class="wp-block-group wt-event__section wt-event__section--judges" id="judges"><!-- wp:pattern {"slug":"helix-wt-page/judges"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"gallery","className":"wt-event__section wt-event__section--gallery","layout":{"type":"default"}} -->
<div class="wp-block-group wt-event__section wt-event__section--gallery" id="gallery"><!-- wp:pattern {"slug":"helix-wt-page/gallery"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"countdown","className":"wt-event__section wt-event__section--countdown","layout":{"type":"default"}} -->
<div class="wp-block-group wt-event__section wt-event__section--countdown" id="countdown"><!-- wp:pattern {"slug":"helix-wt-page/countdown"} /--></div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:html -->
<nav class="wt-event-fixed wt-event-fixed--sp-bottom-bar" aria-label="<?php echo esc_attr__( '固定導線', 'helix-wt' ); ?>"><span class="wt-event-fixed__date"><time datetime="2026-10-15"><?php esc_html_e( '10/15（木）14:00', 'helix-wt' ); ?></time></span><a href="#apply"><?php echo esc_html( $event_action ); ?></a></nav>
<a class="wt-event-fixed wt-event-fixed--float-apply wt-lp-cta-action" href="#apply"><?php echo esc_html( $event_action ); ?></a>
<!-- /wp:html -->
