<?php
/**
 * Title: HP 区間（hero 以外。段 10b で home から分離）
 * Slug: helix-wt/home-sections
 * Categories: helix-wt
 * Description: 段 10b（WT-EVT-0292）: hero 以外の区間・固定導線。$cta は hero 側のみで使う。 2026-09-06 PO 反応 17 回目 WT-EVT-0277「HP ページは？」の Claude 案。hero 6 型・CTA 4 型・区間セット 3 種（企業 HP / サービス / メディア）・お知らせ 4 型・問い合わせ帯 5 型・固定導線 4 型。段8（WT-EVT-0287、台帳 home-event-recapture-v2）: hero +3（cards-carousel / product-shot / search-box）・CTA +1（search）・区間セット +2（店舗・スクール / 学校法人・団体）・問い合わせ帯 +1（double-cta）・固定ページ用パーツ（helix-wt-page/*）を区間として転用。
 *              既定は台帳 research-r17（HP 39 件）の最多型。文言・数値・社名は PoC 用の架空。フォームは送信しない（action="#" method="get"、type="button"）。
 */
$u = get_theme_file_uri( 'assets/img' );
?>
<!-- wp:group {"className":"wt-home__sections","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__sections">

<!-- wp:html -->
<section class="wt-home__section wt-home__section--news" id="news" aria-labelledby="home-news-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">NEWS</p><h2 id="home-news-title"><?php esc_html_e( 'お知らせ', 'helix-wt' ); ?></h2>
<ul class="wt-home-news wt-home-news--list-with-date"><li><time datetime="2026-09-01">2026.09.01</time><span class="wt-home-news__cat"><?php esc_html_e( 'お知らせ', 'helix-wt' ); ?></span><a href="#news"><?php esc_html_e( '秋の無料相談会（オンライン）の受付を始めました', 'helix-wt' ); ?></a></li><li><time datetime="2026-08-20">2026.08.20</time><span class="wt-home-news__cat"><?php esc_html_e( '導入事例', 'helix-wt' ); ?></span><a href="#news"><?php esc_html_e( '製造業の導入事例を公開しました', 'helix-wt' ); ?></a></li><li><time datetime="2026-08-05">2026.08.05</time><span class="wt-home-news__cat"><?php esc_html_e( 'お知らせ', 'helix-wt' ); ?></span><a href="#news"><?php esc_html_e( '夏季休業のご案内', 'helix-wt' ); ?></a></li><li><time datetime="2026-07-15">2026.07.15</time><span class="wt-home-news__cat"><?php esc_html_e( 'メディア', 'helix-wt' ); ?></span><a href="#news"><?php esc_html_e( '業界誌に代表のインタビューが掲載されました', 'helix-wt' ); ?></a></li></ul>
<div class="wt-home-news wt-home-news--tabs"><div class="wt-home-tabs" role="tablist" aria-label="<?php echo esc_attr__( 'お知らせの種類', 'helix-wt' ); ?>"><button type="button" role="tab" aria-selected="true" aria-controls="home-news-tab-all" id="home-news-tabbtn-all"><?php esc_html_e( 'すべて', 'helix-wt' ); ?></button><button type="button" role="tab" aria-selected="false" aria-controls="home-news-tab-news" id="home-news-tabbtn-news" tabindex="-1"><?php esc_html_e( 'お知らせ', 'helix-wt' ); ?></button><button type="button" role="tab" aria-selected="false" aria-controls="home-news-tab-blog" id="home-news-tabbtn-blog" tabindex="-1"><?php esc_html_e( 'ブログ', 'helix-wt' ); ?></button></div><ul id="home-news-tab-all" role="tabpanel" aria-labelledby="home-news-tabbtn-all"><li><time datetime="2026-09-01">2026.09.01</time><a href="#news"><?php esc_html_e( '秋の無料相談会（オンライン）の受付を始めました', 'helix-wt' ); ?></a></li><li><time datetime="2026-08-20">2026.08.20</time><a href="#news"><?php esc_html_e( '製造業の導入事例を公開しました', 'helix-wt' ); ?></a></li><li><time datetime="2026-08-05">2026.08.05</time><a href="#news"><?php esc_html_e( '夏季休業のご案内', 'helix-wt' ); ?></a></li></ul><ul id="home-news-tab-news" role="tabpanel" aria-labelledby="home-news-tabbtn-news" hidden><li><time datetime="2026-09-01">2026.09.01</time><a href="#news"><?php esc_html_e( '秋の無料相談会（オンライン）の受付を始めました', 'helix-wt' ); ?></a></li></ul><ul id="home-news-tab-blog" role="tabpanel" aria-labelledby="home-news-tabbtn-blog" hidden><li><time datetime="2026-08-20">2026.08.20</time><a href="#news"><?php esc_html_e( '製造業の導入事例を公開しました', 'helix-wt' ); ?></a></li></ul><p class="wt-lp-section__note"><?php esc_html_e( 'タブの切替は PoC では静的（見た目の型のみ）。', 'helix-wt' ); ?></p></div>
<ul class="wt-home-news wt-home-news--cards"><li><a href="#news"><img src="<?php echo esc_url( $u ); ?>/media-pickup-5.jpg" alt="" width="640" height="360" loading="lazy" decoding="async"><time datetime="2026-09-01">2026.09.01</time><b><?php esc_html_e( '秋の無料相談会（オンライン）の受付を始めました', 'helix-wt' ); ?></b></a></li><li><a href="#news"><img src="<?php echo esc_url( $u ); ?>/media-pickup-6.jpg" alt="" width="640" height="360" loading="lazy" decoding="async"><time datetime="2026-08-20">2026.08.20</time><b><?php esc_html_e( '製造業の導入事例を公開しました', 'helix-wt' ); ?></b></a></li><li><a href="#news"><img src="<?php echo esc_url( $u ); ?>/media-pickup-2.jpg" alt="" width="640" height="360" loading="lazy" decoding="async"><time datetime="2026-07-15">2026.07.15</time><b><?php esc_html_e( '業界誌に代表のインタビューが掲載されました', 'helix-wt' ); ?></b></a></li></ul>
<p class="wt-home-news__more"><a href="#news"><?php esc_html_e( 'お知らせ一覧', 'helix-wt' ); ?> <i class="wt-i wt-i--s wt-i--arrow-right" aria-hidden="true"></i></a></p></div></section>

<section class="wt-home__section wt-home__section--service-cards" id="service" aria-labelledby="home-service-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">SERVICE</p><h2 id="home-service-title"><?php esc_html_e( 'サービス', 'helix-wt' ); ?></h2>
<ul class="wt-home-cards wt-home-cards--3"><li><a href="#service"><i class="wt-i wt-i--xl wt-i--target" aria-hidden="true"></i><b><?php esc_html_e( '業務診断', 'helix-wt' ); ?></b><span><?php esc_html_e( '現状の作業と手戻りを 2 週間で棚卸しし、改善の順番を決めます。', 'helix-wt' ); ?></span></a></li><li><a href="#service"><i class="wt-i wt-i--xl wt-i--wrench" aria-hidden="true"></i><b><?php esc_html_e( '仕組みづくり', 'helix-wt' ); ?></b><span><?php esc_html_e( '台帳・申請・記録を一つの流れにし、担当が変わっても回る形にします。', 'helix-wt' ); ?></span></a></li><li><a href="#service"><i class="wt-i wt-i--xl wt-i--trend" aria-hidden="true"></i><b><?php esc_html_e( '定着支援', 'helix-wt' ); ?></b><span><?php esc_html_e( '月 1 回の振り返りで数字を確認し、次の改善を決めます。', 'helix-wt' ); ?></span></a></li></ul></div></section>

<section class="wt-home__section wt-home__section--features" id="features" aria-labelledby="home-features-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">WHY US</p><h2 id="home-features-title"><?php esc_html_e( '選ばれる 3 つの理由', 'helix-wt' ); ?></h2>
<ul class="wt-home-features"><li><img src="<?php echo esc_url( $u ); ?>/feature-1.png" alt="" width="160" height="160" loading="lazy" decoding="async"><b><?php esc_html_e( '成果から逆算した設計', 'helix-wt' ); ?></b><span><?php esc_html_e( '目標の問い合わせ数や作業時間から必要な流れを決め、見た目から入りません。', 'helix-wt' ); ?></span></li><li><img src="<?php echo esc_url( $u ); ?>/feature-2.png" alt="" width="160" height="160" loading="lazy" decoding="async"><b><?php esc_html_e( '現場と同じ言葉で', 'helix-wt' ); ?></b><span><?php esc_html_e( '専門用語を使わず、現場の担当者が読める手順書で引き渡します。', 'helix-wt' ); ?></span></li><li><img src="<?php echo esc_url( $u ); ?>/feature-3.png" alt="" width="160" height="160" loading="lazy" decoding="async"><b><?php esc_html_e( '数字で振り返る', 'helix-wt' ); ?></b><span><?php esc_html_e( '導入後も月次で数字を見て、次の一手を一緒に決めます。', 'helix-wt' ); ?></span></li></ul></div></section>

<section class="wt-home__section wt-home__section--numbers" id="numbers" aria-labelledby="home-numbers-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">NUMBERS</p><h2 id="home-numbers-title"><?php esc_html_e( '数字で見る支援実績', 'helix-wt' ); ?></h2>
<ul class="wt-home-numbers"><li><b>320<small><?php esc_html_e( '社', 'helix-wt' ); ?></small></b><span><?php esc_html_e( '支援実績', 'helix-wt' ); ?></span></li><li><b>2.4<small><?php esc_html_e( '倍', 'helix-wt' ); ?></small></b><span><?php esc_html_e( '問い合わせ数の中央値（6 か月後）', 'helix-wt' ); ?></span></li><li><b>93<small>%</small></b><span><?php esc_html_e( '契約継続率', 'helix-wt' ); ?></span></li></ul><p class="wt-lp-section__note"><?php esc_html_e( '数値は PoC 用の架空値。実運用では調査条件と母数を併記する。', 'helix-wt' ); ?></p></div></section>

<section class="wt-home__section wt-home__section--cases" id="cases" aria-labelledby="home-cases-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">CASES</p><h2 id="home-cases-title"><?php esc_html_e( '導入事例', 'helix-wt' ); ?></h2>
<ul class="wt-home-cards wt-home-cards--cases"><li><a href="#cases"><img src="<?php echo esc_url( $u ); ?>/case-factory.jpg" alt="" width="640" height="400" loading="lazy" decoding="async"><small><?php esc_html_e( '製造業・従業員 40 名', 'helix-wt' ); ?></small><b><?php esc_html_e( '日報の転記をなくし、月 30 時間を削減', 'helix-wt' ); ?></b></a></li><li><a href="#cases"><img src="<?php echo esc_url( $u ); ?>/case-tax.jpg" alt="" width="640" height="400" loading="lazy" decoding="async"><small><?php esc_html_e( '士業・従業員 12 名', 'helix-wt' ); ?></small><b><?php esc_html_e( '問い合わせ対応を 1 本化し、返信を翌営業日以内に', 'helix-wt' ); ?></b></a></li><li><a href="#cases"><img src="<?php echo esc_url( $u ); ?>/case-clinic.jpg" alt="" width="640" height="400" loading="lazy" decoding="async"><small><?php esc_html_e( '医療・スタッフ 25 名', 'helix-wt' ); ?></small><b><?php esc_html_e( '予約と問診の流れを整え、待ち時間を 2 割短縮', 'helix-wt' ); ?></b></a></li></ul></div></section>

<section class="wt-home__section wt-home__section--price" id="price" aria-labelledby="home-price-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">PRICE</p><h2 id="home-price-title"><?php esc_html_e( '料金', 'helix-wt' ); ?></h2>
<ul class="wt-home-price"><li><b><?php esc_html_e( '診断', 'helix-wt' ); ?></b><p class="wt-home-price__num">20<small><?php esc_html_e( '万円〜', 'helix-wt' ); ?></small></p><span><?php esc_html_e( '2 週間の棚卸しと改善提案書', 'helix-wt' ); ?></span></li><li class="is-featured"><b><?php esc_html_e( '仕組みづくり', 'helix-wt' ); ?></b><p class="wt-home-price__num"><?php esc_html_e( '月 15', 'helix-wt' ); ?><small><?php esc_html_e( '万円〜', 'helix-wt' ); ?></small></p><span><?php esc_html_e( '3 か月の伴走と手順書の引き渡し', 'helix-wt' ); ?></span></li><li><b><?php esc_html_e( '定着支援', 'helix-wt' ); ?></b><p class="wt-home-price__num"><?php esc_html_e( '月 5', 'helix-wt' ); ?><small><?php esc_html_e( '万円〜', 'helix-wt' ); ?></small></p><span><?php esc_html_e( '月 1 回の振り返り', 'helix-wt' ); ?></span></li></ul><p class="wt-lp-section__note"><?php esc_html_e( '価格は PoC 用の架空値（税別表記の例）。', 'helix-wt' ); ?></p></div></section>

<section class="wt-home__section wt-home__section--faq" id="faq" aria-labelledby="home-faq-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">FAQ</p><h2 id="home-faq-title"><?php esc_html_e( 'よくある質問', 'helix-wt' ); ?></h2>
<div class="wt-home-faq"><details><summary><?php esc_html_e( '相談は無料ですか', 'helix-wt' ); ?></summary><p><?php esc_html_e( '初回の 60 分は無料です。診断以降は料金表のとおりです。', 'helix-wt' ); ?></p></details><details><summary><?php esc_html_e( '対応地域はどこですか', 'helix-wt' ); ?></summary><p><?php esc_html_e( 'オンラインで全国対応、訪問は関東圏が中心です。', 'helix-wt' ); ?></p></details><details><summary><?php esc_html_e( '小規模でも依頼できますか', 'helix-wt' ); ?></summary><p><?php esc_html_e( '従業員 5 名からの実績があります。', 'helix-wt' ); ?></p></details></div></div></section>

<section class="wt-home__section wt-home__section--company" id="company" aria-labelledby="home-company-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">COMPANY</p><h2 id="home-company-title"><?php esc_html_e( '会社概要', 'helix-wt' ); ?></h2>
<table class="wt-home-company"><tbody><tr><th scope="row"><?php esc_html_e( '会社名', 'helix-wt' ); ?></th><td><?php esc_html_e( 'サンプル株式会社（架空）', 'helix-wt' ); ?></td></tr><tr><th scope="row"><?php esc_html_e( '所在地', 'helix-wt' ); ?></th><td><?php esc_html_e( '設定された所在地', 'helix-wt' ); ?></td></tr><tr><th scope="row"><?php esc_html_e( '設立', 'helix-wt' ); ?></th><td><?php esc_html_e( '2016 年 4 月', 'helix-wt' ); ?></td></tr><tr><th scope="row"><?php esc_html_e( '代表者', 'helix-wt' ); ?></th><td><?php esc_html_e( '代表取締役 サンプル 太郎', 'helix-wt' ); ?></td></tr><tr><th scope="row"><?php esc_html_e( '事業内容', 'helix-wt' ); ?></th><td><?php esc_html_e( '業務改善支援、社内システムの設計・導入支援', 'helix-wt' ); ?></td></tr></tbody></table></div></section>

<section class="wt-home__section wt-home__section--access" id="access" aria-labelledby="home-access-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">ACCESS</p><h2 id="home-access-title"><?php esc_html_e( 'アクセス', 'helix-wt' ); ?></h2>
<div class="wt-home-access"><div class="wt-home-map" role="img" aria-label="<?php echo esc_attr__( '地図の表示枠（PoC 用のダミー。実運用では地図画像または埋め込みを置く）', 'helix-wt' ); ?>"><span>MAP</span></div><address><b><?php esc_html_e( 'サンプル株式会社', 'helix-wt' ); ?></b><br><?php esc_html_e( '設定された所在地', 'helix-wt' ); ?><br><?php esc_html_e( '最寄り駅から徒歩 5 分（PoC 用の文言）', 'helix-wt' ); ?></address></div></div></section>

<section class="wt-home__section wt-home__section--contact" id="contact" aria-labelledby="home-contact-title"><div class="wt-lp-section-inner">
<div class="wt-home-contact wt-home-contact--tel-form"><div class="wt-home-contact__tel"><p class="wt-eyebrow">CONTACT</p><h2 id="home-contact-title"><?php esc_html_e( 'お問い合わせ', 'helix-wt' ); ?></h2><a class="wt-home-tel wt-home-tel--big" href="tel:0000000000"><i class="wt-i wt-i--phone" aria-hidden="true"></i><span><b>000-000-0000</b><small><?php esc_html_e( '平日 9:00-18:00', 'helix-wt' ); ?></small></span></a></div><form class="wt-lp-form-inline wt-home-form" action="#contact" method="get" data-wt-poc-form="no-submit"><div class="wt-lp-form__grid"><div><label for="home-f-name"><?php esc_html_e( 'お名前', 'helix-wt' ); ?></label><input id="home-f-name" name="name" type="text" autocomplete="name" required></div><div><label for="home-f-email"><?php esc_html_e( 'メールアドレス', 'helix-wt' ); ?></label><input id="home-f-email" name="email" type="email" autocomplete="email" required></div><div class="is-wide"><label for="home-f-body"><?php esc_html_e( 'ご相談内容', 'helix-wt' ); ?></label><textarea id="home-f-body" name="body" rows="3"></textarea></div></div><button class="wt-lp-cta-action" type="button" aria-describedby="home-f-note"><?php esc_html_e( '送信する', 'helix-wt' ); ?></button><p id="home-f-note" class="wt-lp-form__note"><?php esc_html_e( 'PoC のため送信されません。', 'helix-wt' ); ?></p></form></div>
<div class="wt-home-contact wt-home-contact--form-only"><p class="wt-eyebrow">CONTACT</p><h2><?php esc_html_e( 'お問い合わせ', 'helix-wt' ); ?></h2><form class="wt-lp-form-inline wt-home-form" action="#contact" method="get" data-wt-poc-form="no-submit"><div class="wt-lp-form__grid"><div><label for="home-f2-name"><?php esc_html_e( 'お名前', 'helix-wt' ); ?></label><input id="home-f2-name" name="name" type="text" autocomplete="name" required></div><div><label for="home-f2-email"><?php esc_html_e( 'メールアドレス', 'helix-wt' ); ?></label><input id="home-f2-email" name="email" type="email" autocomplete="email" required></div></div><button class="wt-lp-cta-action" type="button" aria-describedby="home-f2-note"><?php esc_html_e( '送信する', 'helix-wt' ); ?></button><p id="home-f2-note" class="wt-lp-form__note"><?php esc_html_e( 'PoC のため送信されません。', 'helix-wt' ); ?></p></form></div>
<div class="wt-home-contact wt-home-contact--tel-only"><p class="wt-eyebrow">CONTACT</p><h2><?php esc_html_e( 'お電話でのお問い合わせ', 'helix-wt' ); ?></h2><a class="wt-home-tel wt-home-tel--big" href="tel:0000000000"><i class="wt-i wt-i--phone" aria-hidden="true"></i><span><b>000-000-0000</b><small><?php esc_html_e( '平日 9:00-18:00（PoC 用のダミー番号）', 'helix-wt' ); ?></small></span></a></div>
<div class="wt-home-contact wt-home-contact--double-cta"><p class="wt-eyebrow">CONTACT</p><h2><?php esc_html_e( 'お問い合わせ・資料請求', 'helix-wt' ); ?></h2><div class="wt-home-contact__two"><div><i class="wt-i wt-i--xl wt-i--mail" aria-hidden="true"></i><b><?php esc_html_e( '相談したい', 'helix-wt' ); ?></b><p><?php esc_html_e( '課題の整理から一緒に。初回 60 分は無料。', 'helix-wt' ); ?></p><a class="wt-lp-cta-action" href="#contact"><?php esc_html_e( 'フォームで問い合わせ', 'helix-wt' ); ?></a></div><div><i class="wt-i wt-i--xl wt-i--download" aria-hidden="true"></i><b><?php esc_html_e( 'まず資料が欲しい', 'helix-wt' ); ?></b><p><?php esc_html_e( '3 分で読める診断ガイドを PDF で。', 'helix-wt' ); ?></p><a class="wt-lp-cta-action wt-lp-cta-action--secondary" href="/lp/"><?php esc_html_e( '資料をダウンロード', 'helix-wt' ); ?></a></div></div><p class="wt-lp-form__note"><?php esc_html_e( '2 面の CTA（台帳 v2: hero_cta=double 44%、contact 帯に転用）。リンク先は PoC のダミー。', 'helix-wt' ); ?></p></div>
<div class="wt-home-contact wt-home-contact--line"><p class="wt-eyebrow">CONTACT</p><h2><?php esc_html_e( 'LINE で気軽に相談', 'helix-wt' ); ?></h2><a class="wt-lp-line__btn" href="#contact" rel="nofollow"><span class="wt-lp-line__mark" aria-hidden="true"><i class="wt-i wt-i--bubble"></i></span><?php esc_html_e( 'LINE で友だち追加', 'helix-wt' ); ?></a><p class="wt-lp-form__note"><?php esc_html_e( '返信は営業時間内。リンク先は PoC のダミー。', 'helix-wt' ); ?></p></div>
</div></section>

<section class="wt-home__section wt-home__section--cta-band wt-lp-cta-band" id="cta" aria-labelledby="home-cta-title"><div class="wt-lp-cta-band__inner"><p class="wt-eyebrow">NEXT STEP</p><h2 id="home-cta-title"><?php esc_html_e( 'まずは 60 分の無料相談から。', 'helix-wt' ); ?></h2><p><?php esc_html_e( '現状の課題を整理し、次の一歩を一緒に決めます。', 'helix-wt' ); ?></p><a class="wt-lp-cta-action" href="#contact"><?php esc_html_e( '無料で相談する', 'helix-wt' ); ?></a></div></section>

<section class="wt-home__section wt-home__section--category-cards" id="categories" aria-labelledby="home-categories-title"><div class="wt-lp-section-inner"><p class="wt-eyebrow">CATEGORY</p><h2 id="home-categories-title"><?php esc_html_e( 'カテゴリから探す', 'helix-wt' ); ?></h2>
<ul class="wt-home-cards wt-home-cards--4"><li><a href="/category/topic-index/"><i class="wt-i wt-i--l wt-i--grid" aria-hidden="true"></i><b><?php esc_html_e( 'カテゴリ一覧', 'helix-wt' ); ?></b></a></li><li><a href="/category/topic-one/"><i class="wt-i wt-i--l wt-i--file" aria-hidden="true"></i><b><?php esc_html_e( '最初の読みもの', 'helix-wt' ); ?></b></a></li><li><a href="/category/topic-two/"><i class="wt-i wt-i--l wt-i--chart" aria-hidden="true"></i><b><?php esc_html_e( '比較の読みもの', 'helix-wt' ); ?></b></a></li><li><a href="/category/topic-three/"><i class="wt-i wt-i--l wt-i--check-circle" aria-hidden="true"></i><b><?php esc_html_e( '選び方', 'helix-wt' ); ?></b></a></li></ul></div></section>

<section class="wt-home__section wt-home__section--banner-row" id="banners" aria-label="<?php echo esc_attr__( 'バナー', 'helix-wt' ); ?>"><div class="wt-lp-section-inner"><ul class="wt-home-banners"><li><a href="/lp/"><span class="wt-eyebrow">GUIDE</span><b><?php esc_html_e( '3 分の無料診断', 'helix-wt' ); ?></b></a></li><li><a href="/category/topic-two/"><span class="wt-eyebrow">RANKING</span><b><?php esc_html_e( '今月の比較ランキング', 'helix-wt' ); ?></b></a></li><li><a href="#news"><span class="wt-eyebrow">EVENT</span><b><?php esc_html_e( '秋の無料相談会', 'helix-wt' ); ?></b></a></li></ul></div></section>
<!-- /wp:html -->

<!-- wp:group {"anchor":"greeting","className":"wt-home__section wt-home__section--greeting","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__section wt-home__section--greeting" id="greeting"><!-- wp:pattern {"slug":"helix-wt-page/greeting"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"logos","className":"wt-home__section wt-home__section--logos","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__section wt-home__section--logos" id="logos"><!-- wp:pattern {"slug":"helix-wt-page/logos-row"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"stores","className":"wt-home__section wt-home__section--stores","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__section wt-home__section--stores" id="stores"><!-- wp:pattern {"slug":"helix-wt-page/stores"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"events","className":"wt-home__section wt-home__section--events","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__section wt-home__section--events" id="events"><!-- wp:pattern {"slug":"helix-wt-page/event-list"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"gallery","className":"wt-home__section wt-home__section--gallery","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__section wt-home__section--gallery" id="gallery"><!-- wp:pattern {"slug":"helix-wt-page/gallery"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"sns","className":"wt-home__section wt-home__section--sns","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__section wt-home__section--sns" id="sns"><!-- wp:pattern {"slug":"helix-wt-page/sns-feed"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"anchor":"history","className":"wt-home__section wt-home__section--history","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__section wt-home__section--history" id="history"><!-- wp:pattern {"slug":"helix-wt-page/timeline"} /--></div>
<!-- /wp:group -->
<!-- wp:html -->
<section class="wt-home__section wt-home__section--recruit" id="recruit" aria-labelledby="home-recruit-title"><div class="wt-lp-section-inner"><div class="wt-home-recruit"><div><p class="wt-eyebrow">RECRUIT</p><h2 id="home-recruit-title"><?php esc_html_e( '一緒に働く仲間を募集しています', 'helix-wt' ); ?></h2><p><?php esc_html_e( '店舗スタッフ・講師・事務（PoC 用の文言。台帳 v2: D で recruit 50%）。', 'helix-wt' ); ?></p><a class="wt-lp-cta-action" href="/lp/"><?php esc_html_e( '採用情報を見る', 'helix-wt' ); ?></a></div><img src="<?php echo esc_url( $u ); ?>/media-pickup-6.jpg" alt="" width="640" height="400" loading="lazy" decoding="async"></div></div></section>
<!-- /wp:html -->

<!-- wp:group {"className":"wt-home__section wt-home__section--article-grid","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__section wt-home__section--article-grid" id="latest"><div class="wt-lp-section-inner">
<!-- wp:paragraph {"className":"wt-eyebrow"} --><p class="wt-eyebrow">LATEST</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( '新着記事', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:query {"queryId":912,"query":{"perPage":6,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","sticky":"exclude","inherit":false},"className":"wt-home-grid"} -->
<div class="wp-block-query wt-home-grid"><!-- wp:post-template {"layout":{"type":"default"}} -->
<!-- wp:group {"className":"wt-home-card","layout":{"type":"default"}} --><div class="wp-block-group wt-home-card"><!-- wp:post-featured-image {"isLink":true,"aspectRatio":"16/9"} /--><!-- wp:post-terms {"term":"category","fontSize":"xs"} /--><!-- wp:post-title {"isLink":true,"level":3,"fontSize":"m"} /--><!-- wp:post-date {"fontSize":"xs"} /--></div><!-- /wp:group -->
<!-- /wp:post-template --></div>
<!-- /wp:query -->
</div></div>
<!-- /wp:group -->

<!-- wp:group {"className":"wt-home__section wt-home__section--ranking","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home__section wt-home__section--ranking" id="ranking"><div class="wt-lp-section-inner">
<!-- wp:paragraph {"className":"wt-eyebrow"} --><p class="wt-eyebrow">RANKING</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'よく読まれている記事', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:query {"queryId":913,"query":{"perPage":5,"pages":0,"offset":0,"postType":"post","order":"asc","orderBy":"title","sticky":"exclude","inherit":false},"className":"wt-home-rank"} -->
<div class="wp-block-query wt-home-rank"><!-- wp:post-template {"layout":{"type":"default"}} -->
<!-- wp:group {"className":"wt-home-rank__item","layout":{"type":"default"}} --><div class="wp-block-group wt-home-rank__item"><!-- wp:post-featured-image {"isLink":true,"aspectRatio":"16/9"} /--><!-- wp:post-title {"isLink":true,"level":3,"fontSize":"m"} /--></div><!-- /wp:group -->
<!-- /wp:post-template --></div>
<!-- /wp:query -->
<!-- wp:paragraph {"className":"wt-lp-section__note"} --><p class="wt-lp-section__note"><?php esc_html_e( 'PoC では閲覧数の集計がないためタイトル順で代用。実運用では計測値で並べる。', 'helix-wt' ); ?></p><!-- /wp:paragraph -->
</div></div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->

<!-- wp:html -->
<nav class="wt-home-fixed wt-home-fixed--sp-bottom-bar" aria-label="<?php echo esc_attr__( '固定導線', 'helix-wt' ); ?>"><a href="tel:0000000000"><i class="wt-i wt-i--s wt-i--phone" aria-hidden="true"></i><?php esc_html_e( '電話する', 'helix-wt' ); ?></a><a href="#contact"><i class="wt-i wt-i--s wt-i--mail" aria-hidden="true"></i><?php esc_html_e( '問い合わせ', 'helix-wt' ); ?></a></nav>
<a class="wt-home-fixed wt-home-fixed--float-cta wt-lp-cta-action" href="#contact"><?php esc_html_e( '無料で相談する', 'helix-wt' ); ?></a>
<a class="wt-home-fixed wt-home-fixed--float-tel" href="tel:0000000000" aria-label="<?php echo esc_attr__( '電話する（PoC 用のダミー番号）', 'helix-wt' ); ?>"><i class="wt-i wt-i--l wt-i--phone" aria-hidden="true"></i></a>
<!-- /wp:html -->
