<?php
/**
 * Title: HP hero（first view。段 10b で home から分離）
 * Slug: helix-wt/home-hero
 * Categories: helix-wt
 * Description: 段 10b（WT-EVT-0292）: HP のサイドバーを hero の下から始めるため、hero 部を helix-wt/home から分離した（wt-side-layout の直下に置き、side_from で grid 配置を切り替える）。 2026-09-06 PO 反応 17 回目 WT-EVT-0277「HP ページは？」の Claude 案。hero 6 型・CTA 4 型・区間セット 3 種（企業 HP / サービス / メディア）・お知らせ 4 型・問い合わせ帯 5 型・固定導線 4 型。段8（WT-EVT-0287、台帳 home-event-recapture-v2）: hero +3（cards-carousel / product-shot / search-box）・CTA +1（search）・区間セット +2（店舗・スクール / 学校法人・団体）・問い合わせ帯 +1（double-cta）・固定ページ用パーツ（helix-wt-page/*）を区間として転用。
 *              既定は台帳 research-r17（HP 39 件）の最多型。文言・数値・社名は PoC 用の架空。フォームは送信しない（action="#" method="get"、type="button"）。
 */
$u = get_theme_file_uri( 'assets/img' );
$cta = function ( $id ) {
	// hero 内 CTA 4 型（body.wt-home-hero-cta-* で 1 つだけ表示）
	echo '<div class="wt-home-cta wt-home-cta--double"><a class="wt-lp-cta-action" href="#contact">お問い合わせ</a><a class="wt-lp-cta-action wt-lp-cta-action--secondary" href="#service">サービスを見る</a></div>';
	echo '<div class="wt-home-cta wt-home-cta--single"><a class="wt-lp-cta-action" href="#contact">お問い合わせ</a></div>';
	echo '<div class="wt-home-cta wt-home-cta--search" role="search" aria-label="サイト内検索"><label class="screen-reader-text" for="home-cta-q-' . $id . '">キーワード</label><input id="home-cta-q-' . $id . '" type="search" name="s" placeholder="例: 業務改善 事例" autocomplete="off"><button type="button" aria-describedby="home-cta-q-note-' . $id . '"><i class="wt-i wt-i--s wt-i--search" aria-hidden="true"></i>検索</button><span id="home-cta-q-note-' . $id . '" class="screen-reader-text">PoC のため検索は動作しない</span></div>';
	echo '<div class="wt-home-cta wt-home-cta--tel-button"><a class="wt-home-tel" href="tel:0000000000"><i class="wt-i wt-i--phone" aria-hidden="true"></i><span><b>000-000-0000</b><small>平日 9:00-18:00</small></span></a><a class="wt-lp-cta-action" href="#contact">フォームで相談</a></div>';
};
?>
<!-- wp:group {"anchor":"home-hero","className":"wt-home-hero-slot","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home-hero-slot" id="home-hero">
<!-- wp:html -->
<div class="wt-home-hero-slot__html">
<section class="wt-home-hero wt-home-hero--text-only" aria-labelledby="home-hero-text-title"><div class="wt-home-hero__inner"><p class="wt-eyebrow">SAMPLE WORKS</p><h1 id="home-hero-text-title">現場の課題を、設計から運用まで一緒に解く。</h1><p class="wt-home-hero__lead">製造・士業・医療の中小企業向けに、業務の見える化と改善を支援する架空の会社です（PoC 用の文言）。</p><?php $cta( 'text' ); ?></div></section>
<section class="wt-home-hero wt-home-hero--slider" aria-roledescription="carousel" aria-label="メインビジュアル"><div class="wt-home-slider__track" tabindex="0">
<div class="wt-home-slider__slide"><img src="<?php echo esc_url( $u ); ?>/media-pickup-1.jpg" alt="" width="1440" height="810" loading="eager" fetchpriority="high" decoding="async"><div class="wt-home-slider__caption"><p class="wt-eyebrow">01</p><h1>現場の課題を、設計から運用まで一緒に解く。</h1><?php $cta( 'slide1' ); ?></div></div>
<div class="wt-home-slider__slide"><img src="<?php echo esc_url( $u ); ?>/media-pickup-2.jpg" alt="" width="1440" height="810" loading="lazy" decoding="async"><div class="wt-home-slider__caption"><p class="wt-eyebrow">02</p><h2>導入事例を公開しました</h2><p>製造・士業・医療の 3 業種で、問い合わせ数と作業時間の変化をまとめています。</p></div></div>
<div class="wt-home-slider__slide"><img src="<?php echo esc_url( $u ); ?>/media-pickup-3.jpg" alt="" width="1440" height="810" loading="lazy" decoding="async"><div class="wt-home-slider__caption"><p class="wt-eyebrow">03</p><h2>秋の無料相談会（オンライン）</h2><p>毎週木曜 15:00〜。1 社 30 分の個別相談です。</p></div></div>
</div><div class="wt-home-slider__nav" hidden><button type="button" data-wt-slide="prev" aria-label="前へ">‹</button><div class="wt-home-slider__dots" aria-label="ページ送り"></div><button type="button" data-wt-slide="next" aria-label="次へ">›</button></div></section>
<section class="wt-home-hero wt-home-hero--fullbleed" data-wt-scrim aria-labelledby="home-hero-full-title"><img class="wt-home-hero__bg" src="<?php echo esc_url( $u ); ?>/hero.png" alt="" width="1440" height="820" loading="eager" fetchpriority="high" decoding="async"><div class="wt-home-hero__inner"><p class="wt-eyebrow">SAMPLE WORKS</p><h1 id="home-hero-full-title">現場の課題を、設計から運用まで一緒に解く。</h1><p class="wt-home-hero__lead">業務の見える化と改善を支援する架空の会社です（PoC 用の文言）。</p><?php $cta( 'full' ); ?></div></section>
<section class="wt-home-hero wt-home-hero--split" aria-labelledby="home-hero-split-title"><div class="wt-home-hero__inner wt-home-hero__grid"><div><p class="wt-eyebrow">SAMPLE WORKS</p><h1 id="home-hero-split-title">現場の課題を、設計から運用まで一緒に解く。</h1><p class="wt-home-hero__lead">業務の見える化と改善を支援する架空の会社です（PoC 用の文言）。</p><?php $cta( 'split' ); ?></div><div class="wt-home-hero__media"><img src="<?php echo esc_url( $u ); ?>/hero.png" alt="" width="720" height="540" loading="eager" fetchpriority="high" decoding="async"></div></div></section>
<section class="wt-home-hero wt-home-hero--video" aria-labelledby="home-hero-video-title"><div class="wt-home-hero__inner wt-home-hero__grid"><div><p class="wt-eyebrow">SAMPLE WORKS</p><h1 id="home-hero-video-title">3 分でわかる、私たちの支援。</h1><p class="wt-home-hero__lead">動画枠の型。PoC では外部動画を埋め込まず、ポスター画像と再生ボタンの見た目だけを置く。</p><?php $cta( 'video' ); ?></div><div class="wt-home-hero__media wt-home-hero__poster"><img src="<?php echo esc_url( $u ); ?>/media-pickup-4.jpg" alt="" width="720" height="405" loading="eager" decoding="async"><button type="button" class="wt-home-hero__play" aria-label="動画を再生（PoC では再生しません）"><i class="wt-i wt-i--arrow-right" aria-hidden="true"></i></button></div></div></section>
<section class="wt-home-hero wt-home-hero--cards-carousel" aria-labelledby="home-hero-cards-title"><div class="wt-home-hero__inner"><p class="wt-eyebrow">SERVICE</p><h1 id="home-hero-cards-title">サービスから探す</h1><p class="wt-home-hero__lead">製品・コースをカードで横送りする hero（台帳 v2: cards-carousel 11%）。PoC 用の文言。</p><?php $cta( 'cards' ); ?><div class="wt-hcar" data-wt-carousel><ul class="wt-hcar__track" tabindex="0" aria-label="サービス一覧（横スクロール）"><li class="wt-hcar__item"><a href="/lp/"><img src="<?php echo esc_url( $u ); ?>/case-factory.jpg" alt="" width="640" height="400" loading="eager" decoding="async"><b>業務診断</b><span>2 週間で改善の順番を決める</span></a></li><li class="wt-hcar__item"><a href="/lp/"><img src="<?php echo esc_url( $u ); ?>/case-tax.jpg" alt="" width="640" height="400" loading="eager" decoding="async"><b>仕組みづくり</b><span>台帳・申請・記録を一つの流れに</span></a></li><li class="wt-hcar__item"><a href="/lp/"><img src="<?php echo esc_url( $u ); ?>/case-clinic.jpg" alt="" width="640" height="400" loading="lazy" decoding="async"><b>定着支援</b><span>月 1 回の振り返りで数字を確認</span></a></li><li class="wt-hcar__item"><a href="/category/topic-index/"><img src="<?php echo esc_url( $u ); ?>/media-pickup-4.jpg" alt="" width="640" height="400" loading="lazy" decoding="async"><b>導入事例</b><span>製造・士業・医療の 3 業種</span></a></li><li class="wt-hcar__item"><a href="/lp/"><img src="<?php echo esc_url( $u ); ?>/media-pickup-5.jpg" alt="" width="640" height="400" loading="lazy" decoding="async"><b>資料ダウンロード</b><span>3 分で読める診断ガイド</span></a></li></ul><div class="wt-hcar__nav" hidden><button type="button" data-wt-slide="prev" aria-label="前へ">‹</button><button type="button" data-wt-slide="next" aria-label="次へ">›</button></div></div></div></section>
<section class="wt-home-hero wt-home-hero--product-shot" aria-labelledby="home-hero-product-title"><div class="wt-home-hero__inner wt-home-hero__grid"><div><p class="wt-eyebrow">PRODUCT</p><h1 id="home-hero-product-title">現場の記録を、1 つのアプリに。</h1><p class="wt-home-hero__lead">製品画像を主役にする hero（台帳 v2: product-shot 7%、B で 33%）。数値・製品名は PoC 用の架空。</p><?php $cta( 'product' ); ?><ul class="wt-home-hero__badges" aria-label="実績（架空値）"><li><b>320</b><small>社</small></li><li><b>93</b><small>% 継続</small></li><li><b>30</b><small>日間 無料</small></li></ul></div><div class="wt-home-hero__media wt-home-hero__media--product"><img src="<?php echo esc_url( $u ); ?>/product-a.png" alt="" width="640" height="640" loading="eager" fetchpriority="high" decoding="async"></div></div></section>
<section class="wt-home-hero wt-home-hero--search-box" aria-labelledby="home-hero-search-title"><div class="wt-home-hero__inner"><p class="wt-eyebrow">FIND</p><h1 id="home-hero-search-title">知りたいことから探す</h1><p class="wt-home-hero__lead">検索欄を主役にする hero（台帳 v2: search-box 2%、メディア C）。PoC のため検索は動作しない。</p><div class="wt-home-search" role="search" aria-label="サイト内検索"><label class="screen-reader-text" for="home-hero-q">キーワード</label><input id="home-hero-q" type="search" name="s" placeholder="例: 業務改善 事例" autocomplete="off"><button type="button"><i class="wt-i wt-i--s wt-i--search" aria-hidden="true"></i>検索</button></div><ul class="wt-home-search__tags" aria-label="よく検索されるキーワード"><li><a href="/category/topic-one/">業務改善</a></li><li><a href="/category/topic-two/">比較</a></li><li><a href="/category/topic-three/">選び方</a></li><li><a href="/category/topic-index/">すべての記事</a></li></ul><?php $cta( 'search' ); ?></div></section>
</div>
<!-- /wp:html -->
<!-- wp:group {"className":"wt-home-hero wt-home-hero--article-grid","layout":{"type":"default"}} -->
<div class="wp-block-group wt-home-hero wt-home-hero--article-grid"><div class="wt-home-hero__inner">
<!-- wp:heading {"level":1,"className":"wt-home-hero__title wt-home-hero__title--grid"} --><h1 class="wp-block-heading wt-home-hero__title wt-home-hero__title--grid">新着記事</h1><!-- /wp:heading -->
<!-- wp:query {"queryId":911,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","sticky":"exclude","inherit":false},"className":"wt-home-grid wt-home-grid--hero"} -->
<div class="wp-block-query wt-home-grid wt-home-grid--hero"><!-- wp:post-template {"layout":{"type":"default"}} -->
<!-- wp:group {"className":"wt-home-card","layout":{"type":"default"}} --><div class="wp-block-group wt-home-card"><!-- wp:post-featured-image {"isLink":true,"aspectRatio":"16/9"} /--><!-- wp:post-terms {"term":"category","fontSize":"xs"} /--><!-- wp:post-title {"isLink":true,"level":2,"fontSize":"l"} /--><!-- wp:post-date {"fontSize":"xs"} /--></div><!-- /wp:group -->
<!-- /wp:post-template --></div>
<!-- /wp:query -->
</div></div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
