<?php
/**
 * Title: 料金 3 プラン
 * Slug: helix-wt/pricing
 * Categories: helix-wt, helix-wt-page
 * Description: 中央を推奨プラン
 */
?>
<!-- wp:group {"anchor":"pricing","className":"wt-section wt-reveal","align":"full","backgroundColor":"surface","layout":{"type":"constrained","wideSize":"1120px"}} -->
<div class="wp-block-group alignfull wt-section wt-reveal has-surface-background-color has-background" id="pricing">
<!-- wp:paragraph {"className":"wt-eyebrow","align":"center"} --><p class="has-text-align-center wt-eyebrow">Pricing</p><!-- /wp:paragraph -->
<!-- wp:heading {"textAlign":"center","style":{"spacing":{"margin":{"top":"0"}}}} --><h2 class="wp-block-heading has-text-align-center" style="margin-top:0"><?php esc_html_e( '料金プラン', 'helix-wt' ); ?></h2><!-- /wp:heading -->
<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"1.5rem","top":"1.5rem"},"margin":{"top":"2rem"}}}} --><div class="wp-block-columns alignwide" style="margin-top:2rem">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-card","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-card"><!-- wp:heading {"level":3,"fontSize":"l"} --><h3 class="wp-block-heading has-l-font-size"><?php esc_html_e( 'ライト', 'helix-wt' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph {"className":"wt-price"} --><p class="wt-price">¥98,000<small><?php esc_html_e( '/月', 'helix-wt' ); ?></small></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-check","fontSize":"s"} --><ul class="wp-block-list is-style-wt-check has-s-font-size"><li><?php esc_html_e( '月 2 本の記事制作', 'helix-wt' ); ?></li><li><?php esc_html_e( '月次レポート', 'helix-wt' ); ?></li><li><?php esc_html_e( 'メール相談', 'helix-wt' ); ?></li></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline","width":100} --><div class="wp-block-button has-custom-width wp-block-button__width-100 is-style-outline"><a class="wp-block-button__link wp-element-button" href="#contact"><?php esc_html_e( '相談する', 'helix-wt' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-card wt-plan--featured","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-card wt-plan--featured"><!-- wp:paragraph --><p><span class="wt-badge"><?php esc_html_e( 'おすすめ', 'helix-wt' ); ?></span></p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"l"} --><h3 class="wp-block-heading has-l-font-size"><?php esc_html_e( 'スタンダード', 'helix-wt' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph {"className":"wt-price"} --><p class="wt-price">¥198,000<small><?php esc_html_e( '/月', 'helix-wt' ); ?></small></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-check","fontSize":"s"} --><ul class="wp-block-list is-style-wt-check has-s-font-size"><li><?php esc_html_e( '月 6 本の記事制作', 'helix-wt' ); ?></li><li><?php esc_html_e( 'LP 改善 月 1 回', 'helix-wt' ); ?></li><li><?php esc_html_e( '月次ミーティング', 'helix-wt' ); ?></li><li><?php esc_html_e( '広告運用の相談', 'helix-wt' ); ?></li></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"cta","textColor":"cta-contrast","width":100} --><div class="wp-block-button has-custom-width wp-block-button__width-100"><a class="wp-block-button__link has-cta-contrast-color has-cta-background-color has-text-color has-background wp-element-button" href="#contact"><?php esc_html_e( '無料で相談する', 'helix-wt' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-card","layout":{"type":"default"}} --><div class="wp-block-group is-style-wt-card"><!-- wp:heading {"level":3,"fontSize":"l"} --><h3 class="wp-block-heading has-l-font-size"><?php esc_html_e( 'プロ', 'helix-wt' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph {"className":"wt-price"} --><p class="wt-price">¥398,000<small><?php esc_html_e( '/月', 'helix-wt' ); ?></small></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-check","fontSize":"s"} --><ul class="wp-block-list is-style-wt-check has-s-font-size"><li><?php esc_html_e( '記事 12 本 + 動画 2 本', 'helix-wt' ); ?></li><li><?php esc_html_e( '専任ディレクター', 'helix-wt' ); ?></li><li><?php esc_html_e( '広告運用込み', 'helix-wt' ); ?></li></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline","width":100} --><div class="wp-block-button has-custom-width wp-block-button__width-100 is-style-outline"><a class="wp-block-button__link wp-element-button" href="#contact"><?php esc_html_e( '相談する', 'helix-wt' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
