<?php
/**
 * Title: 事例（カード 3）
 * Slug: helix-wt/cases
 * Categories: helix-wt
 * Description: 導入事例カード
 */
$u = get_theme_file_uri( "assets/img" );
?>
<!-- wp:group {"className":"wt-section wt-reveal","align":"full","layout":{"type":"constrained","wideSize":"1120px"}} -->
<div class="wp-block-group alignfull wt-section wt-reveal" id="cases">
<!-- wp:paragraph {"className":"wt-eyebrow","align":"center"} --><p class="has-text-align-center wt-eyebrow">Cases</p><!-- /wp:paragraph -->
<!-- wp:heading {"textAlign":"center","style":{"spacing":{"margin":{"top":"0"}}}} --><h2 class="wp-block-heading has-text-align-center" style="margin-top:0">導入事例</h2><!-- /wp:heading -->
<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"1.5rem","top":"1.5rem"},"margin":{"top":"2rem"}}}} --><div class="wp-block-columns alignwide" style="margin-top:2rem">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-card","layout":{"type":"flow"},"style":{"spacing":{"padding":{"top":"0","left":"0","right":"0","bottom":"1.25rem"}}}} --><div class="wp-block-group is-style-wt-card" style="padding:0 0 1.25rem"><!-- wp:group {"className":"wt-photo","style":{"dimensions":{"aspectRatio":"16/9"}},"layout":{"type":"flow"}} --><div class="wp-block-group wt-photo" style="aspect-ratio:16/9"><img src="<?php echo esc_url( $u ); ?>/case-factory.jpg" alt=""></div><!-- /wp:group --><!-- wp:group {"style":{"spacing":{"padding":{"left":"1.25rem","right":"1.25rem"}}},"layout":{"type":"flow"}} --><div class="wp-block-group" style="padding-left:1.25rem;padding-right:1.25rem"><!-- wp:paragraph {"fontSize":"xs","textColor":"mute"} --><p class="has-mute-color has-text-color has-xs-font-size">製造業 ・ 従業員 80 名</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"l"} --><h3 class="wp-block-heading has-l-font-size">問い合わせ月 3 件 → 14 件</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"s","textColor":"mute"} --><p class="has-mute-color has-text-color has-s-font-size">製品ページを用途別に再編し、技術資料の DL 導線を追加。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-card","layout":{"type":"flow"},"style":{"spacing":{"padding":{"top":"0","left":"0","right":"0","bottom":"1.25rem"}}}} --><div class="wp-block-group is-style-wt-card" style="padding:0 0 1.25rem"><!-- wp:group {"className":"wt-photo","style":{"dimensions":{"aspectRatio":"16/9"}},"layout":{"type":"flow"}} --><div class="wp-block-group wt-photo" style="aspect-ratio:16/9"><img src="<?php echo esc_url( $u ); ?>/case-tax.jpg" alt=""></div><!-- /wp:group --><!-- wp:group {"style":{"spacing":{"padding":{"left":"1.25rem","right":"1.25rem"}}},"layout":{"type":"flow"}} --><div class="wp-block-group" style="padding-left:1.25rem;padding-right:1.25rem"><!-- wp:paragraph {"fontSize":"xs","textColor":"mute"} --><p class="has-mute-color has-text-color has-xs-font-size">税理士事務所 ・ 3 拠点</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"l"} --><h3 class="wp-block-heading has-l-font-size">検索流入 2.8 倍、面談予約フォーム化</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"s","textColor":"mute"} --><p class="has-mute-color has-text-color has-s-font-size">相談例の記事化と料金表の明示で、電話依存から脱却。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-card","layout":{"type":"flow"},"style":{"spacing":{"padding":{"top":"0","left":"0","right":"0","bottom":"1.25rem"}}}} --><div class="wp-block-group is-style-wt-card" style="padding:0 0 1.25rem"><!-- wp:group {"className":"wt-photo","style":{"dimensions":{"aspectRatio":"16/9"}},"layout":{"type":"flow"}} --><div class="wp-block-group wt-photo" style="aspect-ratio:16/9"><img src="<?php echo esc_url( $u ); ?>/case-clinic.jpg" alt=""></div><!-- /wp:group --><!-- wp:group {"style":{"spacing":{"padding":{"left":"1.25rem","right":"1.25rem"}}},"layout":{"type":"flow"}} --><div class="wp-block-group" style="padding-left:1.25rem;padding-right:1.25rem"><!-- wp:paragraph {"fontSize":"xs","textColor":"mute"} --><p class="has-mute-color has-text-color has-xs-font-size">クリニック ・ 開業 2 年目</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"l"} --><h3 class="wp-block-heading has-l-font-size">新患の Web 予約率 61%</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"s","textColor":"mute"} --><p class="has-mute-color has-text-color has-s-font-size">SP の予約導線を固定 CTA に集約し、診療案内を 1 画面化。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
