<?php
/**
 * Title: 料金 3 プラン
 * Slug: helix-wt/pricing
 * Categories: helix-wt
 * Description: 中央を推奨プラン
 */
?>
<!-- wp:group {"className":"wt-section wt-reveal","align":"full","backgroundColor":"surface","layout":{"type":"constrained","wideSize":"1120px"}} -->
<div class="wp-block-group alignfull wt-section wt-reveal has-surface-background-color has-background" id="pricing">
<!-- wp:paragraph {"className":"wt-eyebrow","align":"center"} --><p class="has-text-align-center wt-eyebrow">Pricing</p><!-- /wp:paragraph -->
<!-- wp:heading {"textAlign":"center","style":{"spacing":{"margin":{"top":"0"}}}} --><h2 class="wp-block-heading has-text-align-center" style="margin-top:0">料金プラン</h2><!-- /wp:heading -->
<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"1.5rem","top":"1.5rem"},"margin":{"top":"2rem"}}}} --><div class="wp-block-columns alignwide" style="margin-top:2rem">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-card","layout":{"type":"flow"}} --><div class="wp-block-group is-style-wt-card"><!-- wp:heading {"level":3,"fontSize":"l"} --><h3 class="wp-block-heading has-l-font-size">ライト</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"wt-price"} --><p class="wt-price">¥98,000<small>/月</small></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-check","fontSize":"s"} --><ul class="wp-block-list is-style-wt-check has-s-font-size"><li>月 2 本の記事制作</li><li>月次レポート</li><li>メール相談</li></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline","width":100} --><div class="wp-block-button has-custom-width wp-block-button__width-100 is-style-outline"><a class="wp-block-button__link wp-element-button" href="#contact">相談する</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-card wt-plan--featured","layout":{"type":"flow"}} --><div class="wp-block-group is-style-wt-card wt-plan--featured"><!-- wp:paragraph --><p><span class="wt-badge">おすすめ</span></p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"l"} --><h3 class="wp-block-heading has-l-font-size">スタンダード</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"wt-price"} --><p class="wt-price">¥198,000<small>/月</small></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-check","fontSize":"s"} --><ul class="wp-block-list is-style-wt-check has-s-font-size"><li>月 6 本の記事制作</li><li>LP 改善 月 1 回</li><li>月次ミーティング</li><li>広告運用の相談</li></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"cta","textColor":"cta-contrast","width":100} --><div class="wp-block-button has-custom-width wp-block-button__width-100"><a class="wp-block-button__link has-cta-contrast-color has-cta-background-color has-text-color has-background wp-element-button" href="#contact">無料で相談する</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"is-style-wt-card","layout":{"type":"flow"}} --><div class="wp-block-group is-style-wt-card"><!-- wp:heading {"level":3,"fontSize":"l"} --><h3 class="wp-block-heading has-l-font-size">プロ</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"wt-price"} --><p class="wt-price">¥398,000<small>/月</small></p><!-- /wp:paragraph --><!-- wp:list {"className":"is-style-wt-check","fontSize":"s"} --><ul class="wp-block-list is-style-wt-check has-s-font-size"><li>記事 12 本 + 動画 2 本</li><li>専任ディレクター</li><li>広告運用込み</li></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline","width":100} --><div class="wp-block-button has-custom-width wp-block-button__width-100 is-style-outline"><a class="wp-block-button__link wp-element-button" href="#contact">相談する</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
